<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>

<?php if (Mage::getStoreConfig('netcore/general/enable') == 1): ?>
<!-- Netcore Product search Begin-->
<script>
    window.onload = function() {
        smartech('dispatch', 27, <?php echo Mage::helper('fhsmarketing')->getSearchParamsForNetcore(); ?>);
    }
</script>
<!-- End Netcore Product search -->
<?php endif; ?>