<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author theanh
 */
?>
<?php if (Mage::getStoreConfig('netcore/general/enable') == 1): ?>
<!-- Netcore Product Begin-->
<script>
    window.onload = function() {
        smartech('dispatch', "Product View", {"items": [<?php echo Mage::helper('fhsmarketing')->getProductViewNetcore(); ?>]});
    }
</script>
<!-- End Netcore Product -->   
<?php endif; ?> 