<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lamhung
 */
?>
<?php if (Mage::getStoreConfig('suggestion/general/enable') == 1): ?>
<?php $product = Mage::registry('current_product_redis');?>
<!-- Suggestion Product Begin-->
<script>
    jQuery(document).ready(function(){
	Suggestion(SESSION_ID, "Product View", {"items": [<?php echo Mage::helper('fhsmarketing')->getProductViewNetcore($product); ?>]});
    });
</script>
<!-- End Suggestion Product -->   
<?php endif; ?> 
