<?php
$eventId = $this->getData("event_id");
$eventDetail = $this->getEventDetail($eventId);
$gameData = $eventDetail["gameData"];
$mobile = Mage::helper('fhsmobiledetect')->isMobile();
?>
<?php if (Mage::getStoreConfig('game/config/active')): ?>
    <div id="game-block" class="col-md-12" style="text-align: center;">
        <div id="game">
            <div id="gamecontent" style=" margin: auto;cursor: url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . Mage::getStoreConfig('game/config/cursor') ?>'), auto;">
                <div >
                    <div  style="background-image: url('<?php
                    if ($mobile) {
                        echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $gameData["backgroundImage"] . "');  background-size: cover";
                    } else {
                        echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $gameData["backgroundImageWeb"] . "');  background-size: contain;";
                    }
                    ?>;
                          background-position: bottom;
                          background-repeat: no-repeat;
                          min-height: 700px;">
                        <input type="hidden" id="event-id" value="">
                        <div class="gif-anim"    style="position: absolute; top: 30%;left: 0; right: 0;">
                            <div id="main-game" style="width: 300px;display:block;
                                     margin: auto;">
                                <img  src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $gameData['inGameImage'] ?>" alt="">
                            </div>
                        </div>

                        <div id="wheel-game" style="position: absolute; bottom: 20px;left: 0; right: 0;">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 containerbtn">
                                <button class="btnTutor"   
                                        style="background-image: url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $gameData["backgroundBtn"]; ?>')" onclick="showGameTutorial()">
                                    <a href="<?php echo Mage::getBaseUrl() . $gameData["cmsPageUrl"]; ?>" style="color: inherit; text-decoration: inherit;">
                                    <?php echo $gameData['cmsPageBtn']; ?></button>
                                </a>
                                <button 
                                    class="btnTutor loginbtn" 
                                    style="background-image: url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $gameData["backgroundBtn"]; ?>')" onclick="showGifts()">Quà đã trúng</button> 
                                <button
                                    class="btnTutor loginbtn"   
                                    style="background-image: url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $gameData["backgroundBtn"]; ?>')" onclick="shareFacebook()">Chia sẻ</button>
                            </div>
                            <div class="game-popup-gift" >
                                <div class="game-popup-gift-outsite popup-scroll">
                                    <span class='close'>&times;</span>
                                    <div class="game-popup-gift-title">
                                        <h3 class="game-title orange-title">QUÀ ĐÃ TRÚNG</h3>
                                        <h3 class="error"></h3>
                                    </div>
                                </div>
                                <div class="container-center container-padding">
                                    <button class="sharedBtnLeft">
                                        <a href="<?php echo Mage::getBaseUrl() . $gameData["detailCmsPageUrl"]; ?>">
                                            <span class="sharedTitleLeft">Xem chi tiết</span>
                                        </a>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="youama-noti-window-sucess" style="width: <?php if ($mobile) {
                                    echo "350px";
                                } else {
                                    echo "400px";
                                } ?> !important;">
            <div class="youama-window-outside" style="margin: 0;position: relative;">
                <span class="close lg-close" style="top:0%; right:0%;position:absolute; z-index: 1;color: #000;">×</span>
                <div class="youama-window-inside">
                    <div class="youama-window-title">
                        <h3 class="error"></h3>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div  style="display: none;" class="nogame"><?php echo Mage::app()->getLayout()->createBlock('cms/block')->setBlockId(Mage::getStoreConfig('game/config/nogameweb'))->toHtml() ?></div>
<?php endif; ?>
<script type="text/javascript">
    var eventId = "<?php echo $eventId; ?>";
    jQuery(document).ready(function () {
        checkGame();
        jQuery("div.youama-noti-window-sucess .close").click(function () {
            jQuery("div.youama-noti-window-sucess").fadeOut();
            jQuery(".youama-ajaxlogin-cover").fadeOut();
        });

    });
    $jq("#main-game").on('click', function () {
        jQuery('div.youama-ajaxlogin-cover').fadeIn();
        var eventId = "<?php echo $eventId; ?>";
        new Ajax.Request(
                '<?php echo $this->getUrl('event/index/postRandom', array('_secure' => true)) ?>', {
                    method: 'post',
                    parameters: {eventId: eventId},
                    onLoading: function () {
                        jQuery('.youama-ajaxlogin-loader').fadeIn();
                    },
                    onLoaded: function () {
                        jQuery('.youama-ajaxlogin-loader').fadeOut();
                    },
                    onSuccess: function (transport) {
                        if (200 == transport.status) {
                            var result = JSON.parse(transport.responseText);
                            if (result.success) {
                                var giftImage = result.giftImage;

                                var giftDescription = result.giftDescription;
                                var sharedLink = result.sharedLink;

                                var title1 = $jq(document.createElement('div')).append(`<i  class="fa fa-facebook sharedIcon"></i>
                                          <span class="sharedTitleRight">Chia sẻ</span>`);

                                var shareBtn = $jq(document.createElement('button')).addClass("sharedBtn").append(title1).click(function () {
                                    var share = {
                                        method: "share",
                                        href: sharedLink
                                    };
                                    FB.ui(share, function (response) {
                                        if (response && !response.error_message) {
                                            onClickShare(eventId, sharedLink);
                                        }
                                    });
                                });
                                var btndiv = $jq(document.createElement('div')).addClass("btncontainer").append(`
                                    <button class="sharedBtnLeft">
                                        <a href="<?php echo Mage::getBaseUrl() . $gameData["cmsPageUrl"]; ?>">
                                                  <span class="sharedTitleLeft"><?php echo $gameData['cmsPageBtn'] ?></span>
                                         </a>
                                     </button>
                                    `).append(shareBtn);

                                var giftDescView = giftDescription ? (
                                        `<div class="giftDesc">
                                             <div class="giftDescTitle">${giftDescription}</div></div>`) : "";
                                var html = `<div>`
                                        + `<img src="${giftImage}" alt="" class="giftImage" style="width: 100%;">`

                                        + `</img></div>` + giftDescView;

                                var outgame = "<img src='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $gameData["outGameImage"] ?>'>";
                                var html1 = '<div>' + outgame + '</div>';
                                var sub_label = `<div class="sub-label">Fahasa sưu tầm</div>`;
                                
                                jQuery('div.youama-noti-window-sucess h3.error').html(html).append(btndiv).append(sub_label);
                                jQuery('div.youama-noti-window-sucess').fadeIn();
                                jQuery("#main-game").html(html1);
                            } else {
                                if (result.message == "ERR_NEED_LOGIN") {
                                    jQuery(".youama-login-window").fadeIn();
                                } else {
                                    var errorView = "";
                                    if (result.giftImage) {
                                        errorView = `<img src="${result.giftImage}" />`;
                                    } else {
                                        if (result.message == "NO_GIFT") {
                                            errorView = `<div><?php echo Mage::getStoreConfig('game/config/endofgift'); ?></div>`;
                                        } else if (result.message == "REQUIRE_CONFIRM_TELEPHONE") {
                                            var activeView = `<div><a href="<?php echo Mage::getBaseUrl() . "tryout/refer/" ?>"><input type="button" class="sharedBtn sharedTitleRight" value="Kích hoạt"/></a></div>`;
                                            errorView = `<div><div>Vui lòng kích hoạt số điện thoại của bạn</div>${activeView}</div>`;
                                        } else {
                                            errorView = `<div>${result.message}</div>`;
                                        }
                                    }
                                    jQuery('div.youama-noti-window-sucess h3.error').html("<div style='text-align:center;'>" + errorView + "</div>");
                                    jQuery('div.youama-noti-window-sucess').fadeIn();
                                }

                            }
                        } else {
                            jQuery('div.youama-noti-window-sucess h3.error').html("");
                            var errorMess = "<?php echo Mage::getStoreConfig('game/config/errormess'); ?>";
                            jQuery('div.youama-noti-window-sucess h3.error').html("<div style='text-align:center;font-size: 20px;'>" + errorMess + "</div>");
                            jQuery('div.youama-noti-window-sucess').fadeIn();
                        }
                    }
                }
        );
    });
    
    $jq(".youama-noti-window-sucess .close").click(function () {
        var ingame = `<img src='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $gameData["inGameImage"] ?>'>`;
        $jq("#main-game").html(ingame);
    });

    function onClickShare(eventId, sharedLink) {
        new Ajax.Request(
                "<?php echo $this->getUrl('event/index/shareLog', array('_secure' => true)) ?>", {
                    method: 'post',
                    parameters: {eventId: eventId, sharedLink: sharedLink}
                }
        );
    }

    function showGifts() {
        checkGame();
        jQuery('div.game-popup-gift').fadeIn();
        jQuery('div.youama-ajaxlogin-cover').fadeIn();
    }

    jQuery("div.game-popup-gift .close").click(function () {
        jQuery(this).parent().parent().fadeOut();
        jQuery(".youama-ajaxlogin-cover").fadeOut();
    });

    function checkGame() {
        new Ajax.Request(
                "<?php echo $this->getUrl('event/index/checkGame1/', array('_secure' => true)) ?>", {
                    method: "post",
                    parameters: {eventId: eventId},
                    onLoading: function () {
                        jQuery('.youama-ajaxlogin-loader').fadeIn();
                    },
                    onLoaded: function () {
                        jQuery('.youama-ajaxlogin-loader').fadeOut();
                    },
                    onFailure: function (request, status, error) {
                        alert(request.statusText);
                    },
                    onSuccess: function (transport) {
                        if (200 == transport.status) {
                            var params = JSON.parse(transport.responseText);

                            $jq("#game-content").show();
                            if (params.success) {
                                $jq("div.game-popup-buy-turn .customerFpoint").html(Math.round(params.customerFpoint).toLocaleString('en-US'));
                                var giftsView = "";
                                if (params.gifts.length > 0) {
                                    params.gifts.forEach((gift, index) => {
                                        let giftIcon = "";
                                        let couponView = "";
                                        if (gift.giftType == "fpoint") {
                                            giftIcon = `<i class="fa fa-money" style="margin-left: 5px; font-size: 25px;color: #F7931E;"></i>`;
                                        } else if (gift.giftType == "rule" || gift.giftType == "giftrule" || gift.giftType == "partner_coupon") {
                                            giftIcon = `<i class="fa fa-ticket" style="margin:auto;font-size: 25px;color: #F7931E;"></i>`;
                                            if (gift.couponCode) {
                                                couponView = `<div>Mã giảm giá: ${gift.couponCode}</div>`;
                                            }
                                        }
                                        let giftView = ` <div style="margin-left: 20px; margin-right: 20px;">
                                        <div class="row " style="padding: 10px; border-bottom: 1px solid #d4d4d4; display: flex;"> 
                                           <div style="  vertical-align: middle; " class="col-md-3 col-sm-3 col-xs-3">${giftIcon}</div>
                                                <div class="col-md-9 col-sm-9 col-xs-9" style="text-align: left;  ">
                                                    <div>
                                                        <span style="color: black;">${gift.giftName}<span>
                                                    </div>
                                                    ${couponView}
                                                </div>
                                            </div>
                                        </div> `;
                                        giftsView += giftView;
                                    });
                                }
                                jQuery('div.game-popup-gift h3.error').html(giftsView);

                            }

                        }
                    }
                });
    }

    function shareFacebook() {
        let sharedLink = "<?php echo $gameData["shareLink"]; ?>";
        var share = {
            method: "share",
            href: sharedLink
        };
        FB.ui(share, function (response) {
            if (response && !response.error_message) {
                onClickShare(eventId, sharedLink);
            }
        });
    }

</script>

