<?php
    $mobile = Mage::helper('fhsmobiledetect')->isMobile();
?>
<?php if(!$mobile) : ?> 
<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo $this->__('My Account'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul>
            <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>
            <?php 
            unset($_links['downloadable_products']);
            unset($_links['billing_agreements']);
            unset($_links['recurring_profiles']);
            unset($_links['OAuth Customer Tokens']);
            unset($_links['tags']);
            if (Mage::getStoreConfig("customer/refer_code/enable") !== "1"){
                unset($_links['refer']);
            }
            ?>
            <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current<?php echo ($_last ? ' last' : '') ?>"><strong><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></strong></li>
                <?php else: ?>
                    <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php else :?>
<style type="text/css">
    .col-left.sidebar{
	display: block !important;
    }
/*    .block-content-mobile ul li{
        padding-left: 10px;
    }
    
    .info-user i.fa.fa-chevron-right{
       color: #646464;
       text-align: center;
       line-height: 2;
       float: right;
    }
    .info-user {
        display : flex;
        border-bottom : 1px solid #f2f2f2;
    }
    .block-account .block-content li a ,.block-account .block-content li strong{
        border-bottom: none;
        flex : 0.94;
        padding : 0;
        margin-top : auto;
    }
    .block-account .block-content li a strong{
       line-height: 2;
    }
    .current-mobile{
        font-size: 13;
        color : #F7941E;
    }
    .xem-them-user-info{
        font-size: 15px;
        color: #fff!important;
        font-weight: bold;
        text-align: center;
        padding: 7px;
        background-color: #ff9800;
        width: auto;
        margin: 10px auto;
        display: block;
    }*/

</style>
<div class="block block-account row block-account-mobile " style="margin-top:-15px;">
<div class="block-content no-padding block-content-mobile">
<ul style="background:white;">
   <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>
            <?php 
            unset($_links['downloadable_products']);
            unset($_links['billing_agreements']);
            unset($_links['recurring_profiles']);
            unset($_links['OAuth Customer Tokens']);
            unset($_links['tags']);
	    if(Mage::getStoreConfig("customer/can_use_refer_code/is_active") !== 1){
                unset($_links['refer']);
            }
            ?>
  <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
    
                <?php if ($this->isActive($_link)): ?>
                    
                    <li class="info-user current-mobile<?php echo ($_last ? ' last' : '') ?>"><a href="<?php echo $_link->getUrl() ?>"><strong><?php echo $_link->getLabel() ?></strong><i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                <?php else: ?>
                    <li class="info-user" <?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><strong><?php echo $_link->getLabel() ?></strong><i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                    
                <?php endif; ?>
            <?php endforeach; ?>
</ul>
</div>
</div>

      <a class="xem-them-user-info" href="<?php echo $this->getUrl('customer/account/logout',array('_secure'=>true));?>"><?php echo $this->__('Log Out') ?></a>
                                       
<?php endif; ?>
