<div class="page-title" style="padding: 20px;">
    <h1><?php echo $this->__("My Refer"); ?></h1>
</div>
<?php if (Mage::getStoreConfig("customer/refer_code/enable") == 1): ?>
    <div class="refer-code col-sm-12 col-md-12 col-xs-12" style="background-color: white; padding: 30px;padding-top: 0px;">
        <?php $customer = Mage::getSingleton('customer/session')->getCustomer(); ?>
        <div style="padding: 20px 0; padding-top: 0px;">
            <?php $referCode = $customer->getReferCode(); ?>
            <?php if (isset($referCode)): ?>
                <div id="refer-code">
                    <div class="col-md-12 col-sm-12 col-xs-12 my-refer-code-title"><?php echo $this->__("Your Refer Code:"); ?></div>
                    <div class="col-md-12 col-sm-12 col-xs-12 my-refer-code"><?php echo strtoupper($referCode) ?></div>
                </div>
            <?php else: ?>
                <div id="activate-refer">
                    <div class="activate-refer-title" style=""><?php echo $this->__("Activate refer code"); ?></div>
                    <div style="" class="col-md-6 col-sm-8 col-xs-12 telephone-form">
                        <div class="form-group">
                            <label for="telephone"><?php echo $this->__('Telephone') ?> <span class="required">*</span></label>
                            <input type="text" name="telephone" id="telephone" style="" class="input-text required-entry validate-length maximum-length-11 minimum-length-10 validate-digits" required autocomplete="on" placeholder="VD: 0989123456"/>
                        </div>
                        <div class="form-group">
                            <button type="button" class="sent-otp btn" id="activate-telephone" style=""><?php echo $this->__("Activate") ?></button>
                        </div>
                        <div><i><?php echo $this->__("Note: Only apply for Vietnamese phone numbers"); ?></i></div>
                        <div id="mess-activate-refer" style=""></div>
                    </div>
                </div>
                <div id="telephone-compare">
                    <div style="" class="col-md-6 otp-form">
                        <div class="form-group">
                            <label for="otp"><?php echo $this->__('OTP Code') ?> <span class="required">*</span></label>
                            <input type="text" name="otp" id="otp" style="" class="input-text required-entry"/>
                        </div>
                        <div class="form-group">
                            <button type="button" class="btn" id="compare-otp" style=""><?php echo $this->__("Confirm") ?></button>
                        </div>
                        <div id="telephone-compare-alert" style=""></div>
                    </div>
                    <div style="text-align: center;margin: 30px;">
                        <a href="javascript:void(0);" class="sent-otp" style=""><?php echo $this->__("Resend OTP") ?></a>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
    <div class="refer-code-block col-sm-12 col-md-12 col-xs-12">
        <?php echo Mage::app()->getLayout()->createBlock('cms/block')->setBlockId('refer-code-block')->toHtml(); ?>
    </div>
<?php else: ?>
    <div class="my-refer-code col-sm-12 col-md-12 col-xs-12"><?php echo $this->__("This event is now deactive."); ?></div>
<?php endif; ?>
<script type="text/javascript">
    jQuery(document).ready(function () {
        // resent otp
        jQuery(".sent-otp").click(function () {
            if (validatePhone('telephone')) {
                var telephone = jQuery("input#telephone").val();
                telephone = telephone.replace(/\s/g, "");
                sentOTP(telephone);
            } else {
                jQuery('#mess-activate-refer').html('<?php echo $this->__("Invalid phone number"); ?>');
//                jQuery('#mess-activate-refer').css('color', 'red');
                jQuery('#mess-activate-refer').fadeIn();
            }

        });

        jQuery("#compare-otp").click(function () {
            if (validatePhone('telephone')) {
                var telephone = jQuery("input#telephone").val();
                telephone = telephone.replace(/\s/g, "");
                var otp = jQuery("input#otp").val();
                if (otp.length != 0) {
                    compareOtp(telephone, otp);
                } else {
                    jQuery('#telephone-compare-alert').html('<?php echo $this->__("Invalid OTP"); ?>');
                    jQuery('#telephone-compare-alert').fadeIn();
                }
            } else {
                jQuery('#mess-activate-refer').html('<?php echo $this->__("Invalid phone number"); ?>');
//                jQuery('#mess-activate-refer').css('color', 'red');
                jQuery('#mess-activate-refer').fadeIn();
            }
        });

    });

    function compareOtp(telephone, otp) {
        new Ajax.Request(
                '<?php echo Mage::getBaseUrl() . 'customer/account/compareOtp'; ?>', {
                    method: 'post',
                    parameters: {telephone: telephone, otp: otp},
                    onLoading: function () {
                        jQuery('.youama-ajaxlogin-loader').fadeIn();
                    },
                    onLoaded: function () {
                        jQuery('.youama-ajaxlogin-loader').fadeOut();
                    },
                    onSuccess: function (transport) {
                        if (200 == transport.status) {
                            var key = transport.responseText;
                            switch (key) {

                                case "UPDATE_ENTITY_FALSE":
                                    var mess = "<?php echo $this->__("Your account could not be updated!"); ?>";
                                    jQuery("#telephone-compare-alert").html(mess);
                                    jQuery("#telephone-compare-alert").fadeIn();
                                    break;

                                case "OTP_EXPIRE":
                                    var mess = "<?php echo $this->__("OTP code expires. Please use another OTP code!"); ?>";
                                    jQuery("#telephone-compare-alert").html(mess);
                                    jQuery("#telephone-compare-alert").fadeIn();
                                    break;

                                case "OTP_INVALID":
                                    var mess = "<?php echo $this->__("OTP code does not exist."); ?>";
                                    jQuery("#telephone-compare-alert").html(mess);
                                    jQuery("#telephone-compare-alert").fadeIn();
                                    break;

                                default:
                                    jQuery("#activate-refer").hide();
                                    var mess = "<?php echo $this->__("YOU HAVE SUCCESSFULLY VERIFIED YOUR PHONE NUMBER"); ?>";
                                    jQuery("#telephone-compare").html("<div style='text-align:center;'>" + mess + "</div>");
                                    setTimeout(function(){
                                        location.reload();
                                    }, 2000);
                                    break;
                            }
                        } else {
                            var mess = "<?php echo $this->__("SERVER ERROR. Please try again later!"); ?>";
                            jQuery("#telephone-compare-alert").html(mess);
                            jQuery("#telephone-compare-alert").fadeIn();
                        }
                    }
                }
        );
    }

    function sentOTP(telephone) {
        new Ajax.Request(
                '<?php echo Mage::getBaseUrl() . 'customer/account/checkTelephone'; ?>', {
                    method: 'post',
                    parameters: {telephone: telephone},
                    onLoading: function () {
                        jQuery('.youama-ajaxlogin-loader').fadeIn();
//                        jQuery("#mess-activate-refer").fadeOut();
                    },
                    onLoaded: function () {
                        jQuery('.youama-ajaxlogin-loader').fadeOut();
                    },
                    onSuccess: function (transport) {
                        if (200 == transport.status) {
                            var key = transport.responseText;
                            switch (key) {
                                case "ERROR_SENT_OVERTIMES":
                                    alert("<?php echo $this->__("Too many OTP request attempts. For support, please contact hotline 1900 636467.") ?>");
                                    break;

                                case "SENT_OTP":
                                    jQuery("#telephone-compare").show();
                                    var mess = "<?php echo $this->__("Check your phone for the OTP code"); ?>";
                                    jQuery("#mess-activate-refer").html(mess);
                                    jQuery("#mess-activate-refer").fadeTo(5000, 500).slideUp(500, function () {
                                        jQuery("#mess-activate-refer").slideUp(1000);
                                    });
                                    jQuery("#activate-telephone").hide();
                                    break;

                                case "ERR_TELEPHONE_EXIST":
                                    var mess = "<?php echo $this->__("Phone number have been used by other customer. Please use another phone number!"); ?>";
                                    jQuery("#mess-activate-refer").html(mess);
//                                    jQuery("#mess-activate-refer").fadeIn();
                                    jQuery("#mess-activate-refer").fadeTo(5000, 500).slideUp(500, function () {
                                        jQuery("#mess-activate-refer").slideUp(1000);
                                    });
                                    break;

                                case "SERVER_ERROR":
                                    var mess = "<?php echo $this->__("SERVER ERROR, can't sent otp code. Please try again later!"); ?>";
                                    jQuery("#mess-activate-refer").html(mess);
//                                    jQuery("#mess-activate-refer").fadeIn();
                                    jQuery("#mess-activate-refer").fadeTo(5000, 500).slideUp(500, function () {
                                        jQuery("#mess-activate-refer").slideUp(1000);
                                    });
                                    break;
                            }
                        } else {
                            var mess = "<?php echo $this->__("SERVER ERROR. Please try again later!"); ?>";
                            jQuery("#mess-activate-refer").html(mess);
//                            jQuery("#mess-activate-refer").fadeIn();
                            jQuery("#mess-activate-refer").fadeTo(5000, 500).slideUp(500, function () {
                                jQuery("#mess-activate-refer").slideUp(1000);
                            });
                        }
                    }
                }
        );
    }

    function validatePhone(txtPhone) {
        var a = jQuery("#" + txtPhone).val();
        // trim
        a = a.replace(/\s/g, "");
        var filter = /^[0-9-+]+$/;
        if (filter.test(a)) {
            if (a.length < 9 || a.length > 12) {
                return false;
            } else {
                return true;
            }
        } else {
            return false;
        }
    }
</script>
