<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places&language=en"></script><script type="text/javascript">if((navigator.userAgent.match(/iPhone/i)) || (navigator.userAgent.match(/iPod/i))) {	$$('.onestepcheckout-index-index')[0].addClassName('iphone');}</script>
<?php $styleChange = Mage::helper('onestepcheckout')->getStyle(); ?>
<?php $background_color = Mage::helper('onestepcheckout')->getBackgroundColor($styleChange); ?>
<?php $background_button = Mage::helper('onestepcheckout')->getCheckoutButtonColor(); ?>
<?php if (!$styleChange || $styleChange == 'orange'): ?>
    <?php $styleUse = Mage::helper('onestepcheckout')->getBackgroundColor('orange'); ?>
<?php elseif ($styleChange == 'custom'): ?>
    <?php $styleUse = '#' . Mage::helper('onestepcheckout')->getStyleColor(); ?>
<?php else: ?>
    <?php $styleUse = Mage::helper('onestepcheckout')->getBackgroundColor($styleChange); ?>
<?php endif; ?>
<?php $_helper = Mage::helper('onestepcheckout'); ?>
<style type="text/css">
    .one-step-checkout h3
    {
        background-color:<?php echo $styleUse ?> !important;
    }
    button.onestepcheckout-btn-checkout{
        background:<?php echo $background_button ?> !important;              
    }
    button.onestepcheckout-btn-checkout:hover{
        cursor: pointer;
    }
    button.onestepcheckout-btn-checkout span span{
        font-size:20px !important;
    }

    button#remove_coupon_code_button,
    button#add_coupon_code_button,
    .onestepcheckout-popup-wrapper h1,
    #onestepcheckout-login-popup button.button,
    #onestepcheckout-forgot-button,
    #onestepcheckout-toc-popup h1,
    .onestepcheckout-login-link a span,
    #onestepcheckout-forgot-table li.last p a span,
    #onestepcheckout-register-table li.last p a span,
    p.forgot-link a span,
	p.register-link a span
    {
        background-color:<?php echo $styleUse ?> !important;      

    }
    .onestepcheckout-login-link a,
    p.forgot-link a,
	p.register-link a,
    #onestepcheckout-forgot-table li.last p a,
    #onestepcheckout-register-table li.last p a
    { color:<?php echo $styleUse ?> !important; }
    button#add_coupon_code_button:hover{
        cursor: pointer;
    }

    button#remove_coupon_code_button:hover{
        cursor: pointer;
    }    
    button.place-order-loader span {
        background:none  !important;
    }
    #notify-email-invalid{
            width:250px !important;
            height:70px !important;
            position:fixed !important;
            margin-left:-125px !important;
            margin-top:-50px !important;
            top:50% !important;
            left:50% !important;
            z-index:9999999 !important;
            background:#fff;
            box-shadow: 3px 3px 3px #aaa;
            border-radius:5px;
    }
    #notify-email-invalid-overlay{
            position: fixed !important;
            top: 0 !important;
            left: 0 !important;
            width: 100% !important;
            height: 100% !important;
            z-index:9999998 !important;
            opacity: 0.65;
    }
</style>
<!-- Start: Added by Daniel - 02/04/2015 - set background color for top links buttons after login from OSC -->
<style type='text/css'>
	.onestepcheckout-index-index  #osc_top_links a{
		background:<?php echo $styleUse?>;
	}
</style>
<!-- End: Added by Daniel - 02/04/2015 - set background color for top links buttons after login from OSC -->
<div id="ajaxcart-load-ajax" style="display:none;">
    <div id="load" class="ajaxcart-overlay">&nbsp;</div>
    <div id="ajaxcart-loading" class="ajaxcart-loading">
        <img alt="<?php echo $this->__('Loading') ?>..." src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" /><br />
        <?php echo $this->__('Loading') ?>...
    </div>
    <div id="form-paypal" style="display:none;" class="form-paypal"></div>
</div>
<div class="fhs-co-banner">
    <?php echo $this->getLayout()->createBlock("cms/block")->setBlockId("checkout-block-banner")->toHtml();?>
</div>
<ol class="one-step-checkout clearfix">
    <li>
        <h1 class="checkout_header"><?php echo $this->__('Checkout') ?></h1>
        <p class="subtitle">
            <?php echo $this->__('Fill in the Fields below to complete your purchase!'); ?>
        </p>
    </li>
    <?php if ($this->isShowLoginLink() && !$this->isCustomerLoggedIn()): ?>
        <li id='onestepcheckout_login_link' class="onestepcheckout-login-link">            
            <a href="javascript:void(0);"  id="onestepcheckout-login-link"><span>&nbsp;</span>
                <?php echo $this->__('Already registered?') ?>
                <?php echo $this->__('LOGIN HERE')?>
            </a>
        </li>
    <?php endif ?>
	<!-- Start: Added by Daniel - 02/04/2015 - Top links buttons after login from OSC -->
	<li id='osc_top_links'>
		<a href='<?php echo $this->getUrl('customer/account/',array('_secure'=>true));?>' title='<?php echo $this->__('My Account');?>'><?php echo $this->__('My Account');?></a>
		<a href='<?php echo $this->getUrl('checkout/cart/',array('_secure'=>true));?>' title='<?php echo $this->__('My Cart');?>'><?php echo $this->__('My Cart');?></a>
		<a href='<?php echo $this->getUrl('customer/account/logout',array('_secure'=>true));?>' title='<?php echo $this->__('Log Out');?>'><?php echo $this->__('Log Out');?></a>
	</li>
	<!-- End: Added by Daniel - 02/04/2015 - Top links buttons after login from OSC -->
    <li class='payment_buttons'>
	<?php if(Mage::helper('core')->isModuleEnabled('Amazon_Payments')) echo $this->getChildHtml('amazon_button');?>
    </li>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <li class="address-order">
        <form id="one-step-checkout-form" method="post" action="<?php echo $this->getCheckoutUrl(); ?>">
            <div class="address-information <?php if ($this->configData['page_layout'] == '3columns'): ?>address-info-3-columns<?php endif; ?>">            
			
			<!-- Start: Modified by Daniel -01042015- Reload data after login -->
				<div id='onestepcheckout-billing-section'>
					<?php echo $this->getChildHtml('onestepcheckout.billing'); ?>	
				</div>	
				<div id='onestepcheckout-shipping-section'>				
					<?php echo $this->getChildHtml('onestepcheckout.shipping'); ?>
				</div>
			<!-- End: Modified by Daniel -01042015- Reload data after login -->
			
            </div>
            <?php if ($this->configData['page_layout'] == '3columns'): ?>
                <div class="onestepcheckout-shipping-payment-review">
                <?php endif; ?>
                <?php if ($this->isVirtual() || !Mage::helper('onestepcheckout')->isHideShippingMethod() || $_helper->enabledDelivery()): ?>
                    <div class="order-information <?php if ($this->configData['page_layout'] == '3columns'): ?>order-info-3-columns<?php endif; ?>">
                        <ol>
                            <?php if (!$this->isVirtual() && !Mage::helper('onestepcheckout')->isHideShippingMethod()): ?>
                                <li class="shipping-method">						
                                    <h3 style="float:left"  id="shipping_method_step_header" class="step_2">
                                        <?php echo $this->__('Shipping Method'); ?>
                                    </h3>
                                    <div class="ajax-loader3" id="ajax-shipping" style="display:none; float: left; margin-top: 14px; margin-left: 10px;"></div>
                                    <div class="clear"></div>

                                    <div class="onestepcheckout-shipping-method-section" id="onestepcheckout-shipping-method-section">
                                        <?php echo $this->getChildHtml('onestepcheckout.shipping_method'); ?>						
                                    </div>
                                    <div class="ajax-loader1" id="ajax-loader1" style="display:none;"></div>
                                    <div id="control_overlay_shipping" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 9998; display: none;"></div>
                                </li>
                            <!--2014.18.11 fix hide shipping move check xuong duoi-->
                            <?php endif; ?>

                            <?php if ($_helper->enabledDelivery()): ?>
                                <li class="delivery">
                                    <h3 id="time_of_delivery_header" <?php if (!$this->isVirtual() && !Mage::helper('onestepcheckout')->isHideShippingMethod()): ?> class="step_3" <?php else: ?> class="step_2"<?php endif ?>>
                                        <?php echo $this->__('Time Of Delivery'); ?>
                                    </h3>
                                    <div class="delivery_time_date">
                                        <label for="delivery_date" ><?php echo $this->__('Select a date') ?>: </label>
                                        <p style="float:left;">
                                            <input readonly="readonly" id="delivery_date" type="text" size="7" style="background: none repeat scroll 0 center rgba(0, 0, 0, 0); border: medium none; box-shadow: none; cursor: default; font-weight: bold;" value="<?php echo date('m.d.Y') ?>" name="delivery[onestepcheckout-date]" />
                                            <img src="<?php echo Mage::getBaseUrl('skin') ?>/adminhtml/default/default/images/grid-cal.gif" alt="dateinput" class="v-middle" id="delivery_date_trig" title="dateinput"  />
                                        </p>
                                        <select name="delivery[onestepcheckout-time]" style="margin-left:6px;">
                                            <?php for ($i = 0; $i <= 23; $i++): ?>
                                                <option value="<?php echo str_pad($i, 2, '0', STR_PAD_LEFT) ?>:00"><?php echo str_pad($i, 2, '0', STR_PAD_LEFT) ?>:00</option>
                                            <?php endfor; ?>
                                        </select>
                                    </div>

                                    <link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl('js') ?>calendar/calendar-win2k-1.css"  /> 

                                    <script type="text/javascript">
                                        //<![CDATA[
                                        enUS = {"m": {"wide": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], "abbr": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]}}; // en_US locale reference
                                        Calendar._DN = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]; // full day names
                                        Calendar._SDN = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]; // short day names
                                        Calendar._FD = 0; // First day of the week. "0" means display Sunday first, "1" means display Monday first, etc.
                                        Calendar._MN = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]; // full month names
                                        Calendar._SMN = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]; // short month names
                                        Calendar._am = "AM"; // am/pm
                                        Calendar._pm = "PM";

                                        // tooltips
                                        Calendar._TT = {};
                                        Calendar._TT["INFO"] = "About the calendar";

                                        Calendar._TT["ABOUT"] =
                                            "DHTML Date/Time Selector\n" +
                                            "(c) dynarch.com 2002-2005 / Author: Mihai Bazon\n" +
                                            "For latest version visit: http://www.dynarch.com/projects/calendar/\n" +
                                            "Distributed under GNU LGPL. See http://gnu.org/licenses/lgpl.html for details." +
                                            "\n\n" +
                                            "Date selection:\n" +
                                            "- Use the \xab, \xbb buttons to select year\n" +
                                            "- Use the " + String.fromCharCode(0x2039) + ", " + String.fromCharCode(0x203a) + " buttons to select month\n" +
                                            "- Hold mouse button on any of the above buttons for faster selection.";
                                        Calendar._TT["ABOUT_TIME"] = "\n\n" +
                                            "Time selection:\n" +
                                            "- Click on any of the time parts to increase it\n" +
                                            "- or Shift-click to decrease it\n" +
                                            "- or click and drag for faster selection.";

                                        Calendar._TT["PREV_YEAR"] = "Prev. year (hold for menu)";
                                        Calendar._TT["PREV_MONTH"] = "Prev. month (hold for menu)";
                                        Calendar._TT["GO_TODAY"] = "Go Today";
                                        Calendar._TT["NEXT_MONTH"] = "Next month (hold for menu)";
                                        Calendar._TT["NEXT_YEAR"] = "Next year (hold for menu)";
                                        Calendar._TT["SEL_DATE"] = "Select date";
                                        Calendar._TT["DRAG_TO_MOVE"] = "Drag to move";
                                        Calendar._TT["PART_TODAY"] = ' (' + "Today" + ')';

                                        // the following is to inform that "%s" is to be the first day of week
                                        Calendar._TT["DAY_FIRST"] = "Display %s first";

                                        // This may be locale-dependent. It specifies the week-end days, as an array
                                        // of comma-separated numbers. The numbers are from 0 to 6: 0 means Sunday, 1
                                        // means Monday, etc.
                                        Calendar._TT["WEEKEND"] = "0,6";

                                        Calendar._TT["CLOSE"] = "Close";
                                        Calendar._TT["TODAY"] = "Today";
                                        Calendar._TT["TIME_PART"] = "(Shift-)Click or drag to change value";

                                        // date formats
                                        Calendar._TT["DEF_DATE_FORMAT"] = "%b %e, %Y";
                                        Calendar._TT["TT_DATE_FORMAT"] = "%B %e, %Y";

                                        Calendar._TT["WK"] = "Week";
                                        Calendar._TT["TIME"] = "Time:";

                                        CalendarDateObject._LOCAL_TIMZEONE_OFFSET_SECONDS = -28800;


                                        Calendar.setup({
                                            inputField: "delivery_date",
                                            ifFormat: "%m.%d.%Y",
                                            showsTime: false,
                                            button: "delivery_date_trig",
                                            electric: false,
                                            singleClick: true,
                                            disableFunc : function(date) {
                                                var today = new Date();

                                                if(date.getFullYear() < today.getFullYear()){
                                                    return true;
                                                }else if(date.getMonth() < today.getMonth() && date.getFullYear() <= today.getFullYear()) {
                                                    return true;
                                                }else if(date.getDate() < today.getDate() && date.getMonth() <= today.getMonth() && date.getFullYear() <= today.getFullYear()) {
                                                    return true;
                                                }
                                                if(today.getDate() == date.getDate()){
                                                    return false;
                                                }
                                 
                                            }
                                        });
                                        //]]>
                                    </script>

                                </li>
                            <?php endif; ?>

                        </ol>
			<div class="vat-information">
			    <ol>
				<li class="delivery">
                                    <h3 id="time_of_vat_header" class="step_2">
                                        <?php echo strtoupper($this->__('Information Outputting Invoice')); ?>
                                    </h3>
				    <div class="ajax-loader3" id="ajax-shipping" style="display:none; float: left; margin-top: 14px; margin-left: 10px;"></div>
                                    <div class="clear"></div>

                                    <div class="onestepcheckout-vat-method-section" id="onestepcheckout-vat-method-section">
                                        <?php echo $this->getChildHtml('onestepcheckout.vat_method'); ?>						
                                    </div>
				    <div class="clear"></div>
				</li>
			    </ol>
			</div>
                        <!--2014.18.11 fix 2 column start-->
                        <?php if ($this->configData['page_layout'] == '2columns'): ?>    
                            <ol>
                                <div class="order-review-section" style="width: 100%">
                                    <li class="payment-method">						
                                        <h3 style="float:left" id="payment_method_step_header" <?php if (!$this->isVirtual() && !Mage::helper('onestepcheckout')->isHideShippingMethod() && $_helper->enabledDelivery()): ?> class="step_4"<?php elseif (!$this->isVirtual() && Mage::helper('onestepcheckout')->isHideShippingMethod() && !$_helper->enabledDelivery()): ?>class="step_2"<?php else: ?> class="step_3"<?php endif; ?>>
                                            <?php echo $this->__('Payment Method'); ?>
                                        </h3>	
                                        <div class="ajax-loader3" id="ajax-payment" style="display:none; float: left; margin-top: 14px; margin-left: 10px;"></div>
                                        <div class="clear"></div>
                                        <div id="onestepcheckout-payment-methods" class="onestepcheckout-payment-methods">   
                                            <?php echo $this->getChildHtml('onestepcheckout.payment_method'); ?></div>				<div id="control_overlay_payment" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 9998; display: none;"></div>							
                                    </li> 
                                    <li class="payment-method23534">						
                                        <h3 style="float:left" id="payment_method_step_header" <?php if (!$this->isVirtual() && !Mage::helper('onestepcheckout')->isHideShippingMethod() && $_helper->enabledDelivery()): ?> class="step_4"<?php elseif (!$this->isVirtual() && Mage::helper('onestepcheckout')->isHideShippingMethod() && !$_helper->enabledDelivery()): ?>class="step_2"<?php else: ?> class="step_3"<?php endif; ?>>
                                            <?php echo $this->__('Payment Method'); ?>
                                        </h3>	
                                        <div class="ajax-loader3" id="ajax-payment" style="display:none; float: left; margin-top: 14px; margin-left: 10px;"></div>
                                        <div class="clear"></div>
                                        <div id="onestepcheckout-payment-methods" class="onestepcheckout-payment-methods">   
                                            <?php echo $this->getChildHtml('onestepcheckout.payment_method'); ?></div>				<div id="control_overlay_payment" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 9998; display: none;"></div>							
                                    </li>         
                                </div>
                                <div class="onestepcheckout-review-info">
                                        <li class="order-review-info">	                           
                                            <h3 style="float:left" id="review_step_header" <?php if (!$this->isVirtual() && !Mage::helper('onestepcheckout')->isHideShippingMethod()): ?> class="step_4" <?php else: ?> class="step_3"<?php endif ?>>
                                                <?php echo $this->__('Order Review'); ?>
                                            </h3>			
                                            <div class="ajax-loader3" id="ajax-review" style="display:none; float: left; margin-top: 14px; margin-left: 10px;"></div>
                                            <div class="clear"></div>
                                            <?php echo $this->getChildHtml('onestepcheckout.review') ?>						
                                            <div class="ajax-loader3" id="ajax-loader3"  style="display:none;"></div>
                                            <div id="control_overlay_review" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 9998; display: none;"></div>
                                        </li>                    
                                </div>
                                <div class="button-set clearfix button-onestepcheckout">
                                    <!--
                                    <label for="forgot"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></label>
                                    <br />-->
                                    <div class="clear"></div>
                                    <button style="float:left" onclick="oscPlaceOrder(this);" id="onestepcheckout-button-place-order" type="button" title="<?php echo $this->__('Place Order') ?>" class="btn-proceed-checkout onestepcheckout-btn-checkout onestepcheckout-place">
                                        <span>
                                            <span>
                                                <?php echo $this->__('Place Order') ?>
                                            </span>
                                        </span>
                                    </button>      
                                </div>
                                <div id="onestepcheckout-place-order-loading" style="display:none;margin-top:10px; ">
                                    <!--img style="float:left;" src="<?php echo $styleUse; ?>loading-icon.gif"-->
                                    <p style="float:left;padding-top:5px;">&nbsp;&nbsp;<?php echo $this->__('Please wait, processing your order...') ?></p>
                                </div>
                            </ol>
                        <?php endif; ?>
                        <!--2014.18.11 fix 2 column end-->
                    </div>
                    <!--2014.18.11 fix 2 column start-->
                <?php elseif (!$_helper->enabledDelivery() && Mage::helper('onestepcheckout')->isHideShippingMethod() && $this->hasOnlyOneShippingMethod()): ?>
                    <?php if ($this->configData['page_layout'] == '2columns'): ?>    
                        <div class="order-information order-info-2-columns">
                            <ol>
                                <div class="order-review-section" style="width: 100%">
                                    <li class="payment-method">						
                                        <h3 style="float:left" id="payment_method_step_header" <?php if (!$this->isVirtual() && !Mage::helper('onestepcheckout')->isHideShippingMethod() && $_helper->enabledDelivery()): ?> class="step_4"<?php elseif (!$this->isVirtual() && Mage::helper('onestepcheckout')->isHideShippingMethod() && !$_helper->enabledDelivery()): ?>class="step_2"<?php else: ?> class="step_3"<?php endif; ?>>
                                            <?php echo $this->__('Payment Method'); ?>
                                        </h3>	
                                        <div class="ajax-loader3" id="ajax-payment" style="display:none; float: left; margin-top: 14px; margin-left: 10px;"></div>
                                        <div class="clear"></div>
                                        <div id="onestepcheckout-payment-methods" class="onestepcheckout-payment-methods">   
                                            <?php echo $this->getChildHtml('onestepcheckout.payment_method'); ?></div>				<div id="control_overlay_payment" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 9998; display: none;"></div>							
                                    </li>         
                                </div>
                                <div class="onestepcheckout-review-info">
                                        <li class="order-review-info">	                           
                                            <h3 style="float:left" id="review_step_header" <?php if (!$this->isVirtual() && !Mage::helper('onestepcheckout')->isHideShippingMethod()): ?> class="step_4" <?php else: ?> class="step_3"<?php endif ?>>
                                                <?php echo $this->__('Order Review'); ?>
                                            </h3>			
                                            <div class="ajax-loader3" id="ajax-review" style="display:none; float: left; margin-top: 14px; margin-left: 10px;"></div>
                                            <div class="clear"></div>
                                            <?php echo $this->getChildHtml('onestepcheckout.review') ?>						
                                            <div class="ajax-loader3" id="ajax-loader3"  style="display:none;"></div>
                                            <div id="control_overlay_review" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 9998; display: none;"></div>
                                        </li>                    
                                </div>
                                <div class="button-set clearfix button-onestepcheckout">
                                    <!--
                                    <label for="forgot"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></label>
                                    <br />-->
                                    <div class="clear"></div>
                                    <button style="float:left" onclick="oscPlaceOrder(this);" id="onestepcheckout-button-place-order" type="button" title="<?php echo $this->__('Place Order') ?>" class="btn-proceed-checkout onestepcheckout-btn-checkout onestepcheckout-place">
                                        <span>
                                            <span>
                                                <?php echo $this->__('Place Order') ?>
                                            </span>
                                        </span>
                                    </button>      
                                </div>
                                <div id="onestepcheckout-place-order-loading" style="display:none;margin-top:10px; ">
                                    <!--img style="float:left;" src="<?php echo $styleUse; ?>loading-icon.gif"-->
                                    <p style="float:left;padding-top:5px;">&nbsp;&nbsp;<?php echo $this->__('Please wait, processing your order...') ?></p>
                                </div>
                            </ol>
                        </div>
                    <?php endif; ?>  
                    <!--2014.18.11 fix 2 column end-->
                <?php endif; ?>
                    
                    <!--2014.18.11 fix hide shipping start-->
                <?php if (Mage::helper('onestepcheckout')->isHideShippingMethod()): ?>
                    <?php $_shippingMethod = $this->hasOnlyOneShippingMethod(); ?>
                    <span class="no-display">
                        <input name="shipping_method" type="radio" value="<?php echo $_shippingMethod; ?>" id="s_method_<?php echo $_shippingMethod; ?>" checked="checked" />
                    </span>
               <?php endif; ?>
                    <!--2014.18.11 fix hide shipping end-->
                    

<!--tryout-->

<div class="order-review-section fpoint-method" style="margin-bottom: 20px;">
    <!--tryout-->
                        <ol>
                            <li class="payment-method">						
                                <h3 style="float:left" id="payment_method_step_header_tryout" <?php if (!$this->isVirtual() && !Mage::helper('onestepcheckout')->isHideShippingMethod() && $_helper->enabledDelivery()): ?> class="step_4"<?php elseif (!$this->isVirtual() && Mage::helper('onestepcheckout')->isHideShippingMethod() && !$_helper->enabledDelivery()): ?>class="step_2"<?php else: ?> class="step_3"<?php endif; ?>>
                                    <?php echo $this->__('Membership Fahasa'); ?> (F-Club)
                                </h3>	
                                <?php if(Mage::getSingleton('customer/session')->isLoggedIn()):?>
                                <!--<p class="label"><?php echo $this->__('Do you want to use fpoint to place order?'); ?></p>-->
                                <p class="amount"><span><?php echo $this->__('Amount F-point:'); ?></span> <?php echo Mage::helper('checkout')->formatPrice(Mage::helper('tryout')->determinetryout()); ?></p>
                                
                                <?php $addTryoutUrl = $this->getUrl('onestepcheckout/ajax/add_tryout');?>
                                <div class="onestepcheckout-tryout">
                                    <?php $productNotApplyFpoint = Mage::helper('tryout')->getProductNotApplyFpoint(); ?>
                                    <?php if ($productNotApplyFpoint !== FALSE): ?>
                                        <div class="onestepcheckout-tryout-no-apply">
                                            <span class="title">Sản phẩm không áp dụng thanh toán bằng F-Point:</span>
                                            <ul>
                                                <?php foreach ($productNotApplyFpoint as $p): ?>
                                                    <li>+ <?php echo $p["name"]; ?></li>
                                                <?php endforeach; ?>
                                            </ul>
                                        </div>
                                    <?php else: ?>
                                        <input class="onestepcheckout_tryout_checkbox with-font" type="checkbox" name="onestepcheckout_tryout_checkbox" 
                                               id="onestepcheckout_tryout_checkbox" 
                                               onclick="addTryout('<?php echo $addTryoutUrl ?>');"
                                               value="1" <?php if ($_helper->checkTryoutSession()): ?> checked="checked"<?php endif; ?>/>
                                        <label for="onestepcheckout_tryout_checkbox"><?php echo $this->__('Use F-point for place order'); ?>

                                        </label>
                                    <?php endif; ?>
                                </div>
                                <?php 
                                $freeshipTimes = Mage::helper('freeship')->getFreeShip();
                                // recaculate shipping
                                $addFreeshipUrl = $this->getUrl('onestepcheckout/index/saveAddressOnestepcheckout/');
                                $session = Mage::getSingleton('checkout/session');
                                ?>
                                <p class="amount"><span><?php echo $this->__('Amount freeship: %s times', "<span class='price'>".$freeshipTimes."</span>"); ?></span></p>
                                <div class="onestepcheckout-freeship">
                                    <input class="onestepcheckout_freeship_checkbox with-font" type="checkbox" name="onestepcheckout_freeship_checkbox" 
                                           id="onestepcheckout_freeship_checkbox" 
                                           onclick="addFreeship('<?php echo $addFreeshipUrl ?>');"
                                           value="1" <?php if ($session->getData('onestepcheckout_freeship') == 1): ?> checked="checked"<?php endif;?>/>
                                    <label for="onestepcheckout_freeship_checkbox"><?php echo $this->__('Use Freeship for place order'); ?>
                                    </label>
                                </div>
                                <div class="fpoint_cms_block"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('fpoint_cms_block')->toHtml(); 
?></div>
                                <?php else:?>
                                <p class="label"><?php echo $this->__("Please <a href='' onclick='triggerLogin(); return false;'>%s</a> to use Fpoint.",$this->__("Login"));?></p>
                                <div class="fpoint_cms_block_nologin"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('fpoint_cms_block_nologin')->toHtml(); 
?></div>
                                <?php endif;?>

                            </li>
                        </ol>
                    <!--tryout-->
</div>

<?php // endif;?>


                <?php if ($this->configData['page_layout'] == '3columns'): ?>
                    <!--2014.18.11 fix big hole in 3 column start-->
                    <div class="order-review-section payment-method-section" style="<?php if (Mage::helper('onestepcheckout')->isHideShippingMethod() && !$_helper->enabledDelivery()) if($this->hasOnlyOneShippingMethod()) echo 'width: 100% !important' ;?>">
                    <!--2014.18.11 fix big hole in 3 column end-->
                    
                        <ol>
                            <li class="payment-method">						
                                <h3 style="float:left" id="payment_method_step_header" <?php if (!$this->isVirtual() && !Mage::helper('onestepcheckout')->isHideShippingMethod() && $_helper->enabledDelivery()): ?> class="step_4"<?php elseif (!$this->isVirtual() && Mage::helper('onestepcheckout')->isHideShippingMethod() && !$_helper->enabledDelivery()): ?>class="step_2"<?php else: ?> class="step_3"<?php endif; ?>>
                                    <?php echo $this->__('Payment Method'); ?>
                                </h3>	
                                <div class="ajax-loader3" id="ajax-payment" style="display:none; float: left; margin-top: 14px; margin-left: 10px;"></div>
                                <div class="clear"></div>
                                <div id="onestepcheckout-payment-methods" class="onestepcheckout-payment-methods">   
                                    <?php echo $this->getChildHtml('onestepcheckout.payment_method'); ?></div>				<div id="control_overlay_payment" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 9998; display: none;"></div>							
                            </li>

                        </ol>
                    </div>
                <?php endif; ?>
                <?php if ($this->configData['page_layout'] == '3columns'): ?>
                    <div class="onestepcheckout-review-info">
                        <ol>
                            <li class="order-review-info">	                           
                                <h3 style="float:left" id="review_step_header" <?php if (!$this->isVirtual() && !Mage::helper('onestepcheckout')->isHideShippingMethod()): ?> class="step_4" <?php else: ?> class="step_3"<?php endif ?>>
                                    <?php echo $this->__('Order Review'); ?>
                                </h3>			
                                <div class="ajax-loader3" id="ajax-review" style="display:none; float: left; margin-top: 14px; margin-left: 10px;"></div>
                                <div class="clear"></div>
                                <?php echo $this->getChildHtml('onestepcheckout.review') ?>						
                                <div class="ajax-loader3" id="ajax-loader3"  style="display:none;"></div>
                                <div id="control_overlay_review" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 9998; display: none;"></div>

                            </li>                    
                        </ol>
                    </div>
                    <?php echo $this->getLayout()->createBlock('event/block')->setTemplate('event/gift_event.phtml')->tohtml(); ?>
                    <!-- Block: Buffet Combo With Gift -->
                    <?php if(Mage::getStoreConfig('event_buffetcombo/config/use_gift')): ?>
                    <?php echo $this->getChildHtml('event_buffetcombo_gift'); ?>
                    <?php endif; ?>
		    <!-- EVENT_CART BEGIN -->
                    <?php if (Mage::getStoreConfig('eventcart_config/config/is_active')) : ?>
		    <link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN, true)
			    ."frontend/ma_vanese/fahasa/css/event_cart.css?q="
			    .Mage::getStoreConfig('bubble_queryfier/suffix_js_css/suffix'); ?>" media="all" />
			<div class="clear"></div>
                        <div id="event_cart" style="display: none;">
                            <input type="hidden" id="event_cart_data" name="event_cart" value="0"/>
                            <div class="event_cart_header">
                            </div>
                            <div class="event_cart_notificate" style="display: none;">
				Địa chỉ nhận hàng tại các khu vực sau của nội: <a onclick="eventcart.openNotificationPopup();">Bấm xem chi tiết</a>
                            </div>
                            <div class="event_cart_content">
                            </div>
			    <div class="event_cart_cancel">
				<input class="event_cart_cancel_btn" onclick="eventcart.clearChoice();" type="button" value=""/>
			    </div>
                            <div class="event_cart_resutl" style="display: none;">
                                <div class="event_cart_resutl_title"></div>
                                <div class="event_cart_resutl_content"></div>	
                            </div>
                            <div class="event_cart_footer" style="display: none;">
                            </div>
                            <div class="clear"></div>
                        </div>
		    <div id="fahasa_dialog_wrapper-cover" onclick="$jq('.fahasa_dialog_wrapper').fadeOut();$jq('#fahasa_dialog_wrapper-cover').fadeOut();"></div>
		    <div class="fahasa_dialog_wrapper">
			<a class="fahasa_dialog_wrapper_close" onclick="$jq('.fahasa_dialog_wrapper').fadeOut();$jq('#fahasa_dialog_wrapper-cover').fadeOut();">
			    <div class="fahasa_dialog_wrapper_close_btn">
			    <span class="fa fa-times fa-6"></span>
			    </div>
			</a>
		    <div class="fahasa_dialog">
		      <div class="fahasa_dialog_header">CHI TIẾT ĐIỀU KIỆN CHƯA THỎA</div>
		      <div class="fahasa_dialog_content">
			      <ul class="fahasa_dialog_content_list">
				<li>
				</li>
			    </ul>
		      </div>
		      <div class="fahasa_dialog_footer">
			  <button type="button" onclick="location.href='/checkout/cart/'" class="fahasa_dialog_footer_btn">
				<span>
				    Xem giỏ hàng
				</span>
			    </button>
			    <button type="button" onclick="eventcart.onclickConfirmButton();" class="fahasa_dialog_footer_btn confirm">
				<span>
				    Xem trang chương trình                    
				</span>
			    </button>
		      </div>
		    </div>
		  </div>
                        <script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS, true)."lib/event_cart.js?q=".Mage::getStoreConfig('bubble_queryfier/suffix_js_css/suffix'); ?>"></script>
                        <script type="text/javascript">
                            var eventcart = new EventCart();
                        </script>
                        <?php endif;?>
		    <!-- EVENT_CART END -->
                    <div class="button-set clearfix button-onestepcheckout">
                        <!--
                        <label for="forgot"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></label>
                        <br />-->
                        <div class="clear"></div>
                        <button style="float:left" onclick="oscPlaceOrder(this);" id="onestepcheckout-button-place-order" type="button" title="<?php echo $this->__('Place Order') ?>" class="btn-proceed-checkout onestepcheckout-btn-checkout onestepcheckout-place">
                            <span>
                                <span>
                                    <?php echo $this->__('Place Order') ?>                                    
                                </span>
                            </span>
                        </button>                        
                    </div>
                    <div class="warning-ship-split"><?php // echo $this->__('Your order may be split and ship multiple times!') ?>
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cart_note')->toHtml(); 
?> </div>
                    <div id="onestepcheckout-place-order-loading" style="display:none;margin-top:10px; ">
                        <!--img style="float:left;" src="<?php echo $styleUse; ?>loading-icon.gif"-->
                        <p style="float:left;padding-top:5px;">&nbsp;&nbsp;<?php echo $this->__('Please wait, processing your order...') ?></p>
                    </div>
                </div>

            <?php endif; ?>
            <?php if (!$_helper->isCustomerLoggedIn() && $_helper->showLoginLink()): ?>
                <?php echo $this->getChildHtml('login-popup'); ?>
            <?php endif; ?>			
        </form>
    </li>
</ol>

<div class="duplicated-order-cover"></div>
<div id="duplicated-order">
    <div class="title" style="background-color: #F39801">
        <h2><?php echo $this->__("Duplicated items from current processing orders")?></h2>
        <p><?php echo $this->__("Are you sure to buy?")?></p>
    </div>
    <input hidden="true" id="pass-duplicated-order" value="false">
    <div class="content">
        <table></table>
        <div class="col-sm-12 col-md-12 col-sms-12 confirm-box">
            <div class="col-sm-6 col-md-6 col-sms-6">
                <a id="shopping_cart" href="<?php echo Mage::getBaseUrl(); ?>checkout/cart"><?php echo $this->__("View cart") ?></a> 
            </div>
            <div class="col-sm-6 col-md-6 col-sms-6">
                <a id="duplicated-order-pass" href="javascript:void(0)"><?php echo $this->__("Continue buying") ?></a>
            </div>
        </div>
    </div>
    <div class="cleaner"></div>
</div>

<div id="duplicated-item">
    <div class="title" >
        <h2><?php echo $this->__("Warning") ?></h2>
        <h3><?php echo $this->__("Cart has items with quantity of 2") ?></h3>
    </div>
    <input hidden="true" id="pass-duplicated-item" value="false"> 
    <div class="content col-sm-12 col-md-12 col-sms-12">
        <div class="col-sm-12 col-md-12 col-sms-12 confirm-box">
            <div class="col-sm-6 col-md-6 col-sms-6">
                <a id="shopping_cart" href="<?php echo Mage::getBaseUrl(); ?>checkout/cart"><?php echo $this->__("View cart") ?></a> 
            </div>
            <div class="col-sm-6 col-md-6 col-sms-6">
                <a id="duplicated-item-pass" href="javascript:void(0)"><?php echo $this->__("Place Order") ?></a>
            </div>
        </div>
    </div>
    <div class="cleaner"></div>
</div>

<div id="popup-fahasa-default-cover"></div>
<div id="popup-fahasa-ward">
    <div class="popup-fahasa-default-header-small">
	<?php echo $this->__('CONFIRM INFORMATION') ?>
    </div>
    <div class="popup-fahasa-default-content">
	<div id="update-city-content-select" class="update-city-content-select" style="display: none;">
	    <label for="city" class="required" style="font-weight:bold; margin-left: 20px; width: 96px;"><em>*</em><?php echo $this->__('City') ?>:</label>
	    <select id="city_id_update" style="max-width: 196px; padding: 4px 4px 4px 4px;border-top: none !important;border-left: none !important; border-right: none !important;" name="city_id_update" title="<?php echo $this->__('City') ?>" class="validate-select" defaultValue="">
		<option value=""><?php echo $this->__('Please select City') ?></option>
	    </select>
	    <input type="text" title="<?php echo $this->__('City') ?>" name="city" value="" class="input-text" id="city_update" style="display: none;"/>
	</div>
	<div class="update-ward-content-select">
	    <label for="ward" class="required" style="font-weight:bold; margin-left: 20px; width: 96px;"><em>*</em><?php echo $this->__('Ward') ?>:</label>
	    <select id="ward_id_update" style="max-width: 196px; padding: 4px 4px 4px 4px;border-top: none !important;border-left: none !important; border-right: none !important;" name="ward_id_update" title="<?php echo $this->__('Ward') ?>" class="validate-select" address_id="" defaultValue="">
		<option value=""><?php echo $this->__('Please select Ward') ?></option>
	    </select>
	    <input type="text" title="<?php echo $this->__('Ward') ?>" name="ward" value="" class="input-text" id="ward_update" style="display: none;"/>
	</div>
    </div>
    <div class="popup-fahasa-default-footer-small btn-submit col-lg-12 col-md-12 col-sm-12 col-xs-12">		
	<button id="btn_ward_update-cancel" type="button" onclick="closeUpdateWard();" class="popup-fahasa-default-confirm-small cancel">
	    <span>
		<?php echo $this->__('Cancel') ?>                                    
	    </span>
	</button>
	<button id="btn_ward_update-confirm" type="button" onclick="updateWard();" class="popup-fahasa-default-confirm-small confirm">
	    <span>
		<?php echo $this->__('Confirm') ?>                          
	    </span>
	</button>
    </div>
</div>
<div id="popup-default-loading" style="padding-top: 10px;">
    <div id="popup-default-loading-icon" style="padding: 15px 0;">
	<center><div id="default-icon-loading" style="height: 128px; width: 128px; background: url('<?php echo $this->getSkinUrl('images/fpointstore/loading.png') ?>') no-repeat center center transparent; background-size: 110px;"></div></center>
    </div>
    <div id="popup-default-loading-logo" class="popup-fahasa-alert-logo" style="display: none;">
	<center><img src="<?php echo $this->getSkinUrl('images/logo-alert-fail.png') ?>"></center>
    </div>
    <div class="popup-default-loading-content">
	<div id="popup-default-loading-context-text" class="popup-fahasa-default-content-text" style="padding: 15px;">
	    <?php echo $this->__('Your order has been received and is processing'); ?>...
	</div>
    </div>
    <div class="popup-fahasa-default-footer-small btn-submit col-lg-12 col-md-12 col-sm-12 col-xs-12">
	<button type="button" onclick="orderqueue.tryLoadOrderStatus();" id="popup-default-loading-confirm" class="popup-fahasa-default-alert-confirm" style="display: none;">
	    <span>
		<?php echo $this->__('Try again') ?>                          
	    </span>
	</button>
    </div>
</div>
<div id="popup-fahasa-alert">
    <div class="popup-fahasa-alert-logo">
	<center><img src="<?php echo $this->getSkinUrl('images/logo-alert-fail.png') ?>"></center>
    </div>
    <div class="popup-fahasa-default-alert-content">
	<div class="popup-fahasa-default-content-text">
	    
	</div>
    </div>
    <div class="popup-fahasa-default-footer-small btn-submit col-lg-12 col-md-12 col-sm-12 col-xs-12">
	<button type="button" onclick="$jq('#popup-fahasa-alert').fadeOut();$jq('.youama-ajaxlogin-cover').fadeOut();" class="popup-fahasa-default-alert-confirm">
	    <span>
		<?php echo $this->__('Ok') ?>                          
	    </span>
	</button>
    </div>
</div>
<div id="popup_fahasa_shipping_confirm">
    <div class="popup-fahasa-default-header-small" style="text-transform: uppercase;">
	<?php echo $this->__('Confirm shipping Address') ?>
    </div>
    <div class="popup-fahasa-default-content">
	<div id="shipping_address_confirm_content"></div>
    </div>
    <div class="popup-fahasa-default-footer-small btn-submit col-lg-12 col-md-12 col-sm-12 col-xs-12">		
	<button id="btn_shipping_confirm_cancel" onclick="$jq('#popup_fahasa_shipping_confirm').fadeOut();$jq('.youama-ajaxlogin-cover').fadeOut();"  type="button" class="popup-fahasa-default-confirm-small cancel lg-close">
	    <span>
		<?php echo $this->__('Cancel') ?>                   
	    </span>
	</button>
	<button id="btn_shipping_confirm_confirm" onclick="is_confirm_shipping_addres = false;
							$jq('.youama-ajaxlogin-cover').fadeOut();
							$jq('#popup_fahasa_shipping_confirm').fadeOut();
							oscPlaceOrder(document.getElementById('onestepcheckout-button-place-order'));" 
	type="button" class="popup-fahasa-default-confirm-small confirm">
	    <span>
		<?php echo $this->__('Confirm') ?>                          
	    </span>
	</button>
    </div>
</div>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS, true)."lib/orderqueue.js?q=".Mage::getStoreConfig('bubble_queryfier/suffix_js_css/suffix'); ?>"></script>
<script type="text/javascript">

    //<![CDATA[	
    var preloadImage = '<?php echo $this->getSkinUrl('images/onestepcheckout/preload.gif') ?>';
    var shipping_method_url = '<?php echo $this->getUrl('onestepcheckout/index/save_shipping', array('_secure' => true)); ?>';
    var enable_update_payment = <?php echo $this->configData['update_payment'] ? 'true' : 'false'; ?>;
    var login_url = '<?php echo $this->getUrl('onestepcheckout/index/show_login', array('_secure' => true)); ?>';
    var show_login_link = <?php echo $this->configData['show_login_link'] ? 'true' : 'false'; ?>;
    var show_term_condition_url = '<?php echo $this->getUrl('onestepcheckout/index/show_term_condition', array('_secure' => true)); ?>';
    var form = $('one-step-checkout-form');
    var reload_payment = <?php echo $this->configData['reload_payment']; ?>;
    var text_processing = '<?php echo $this->__('Your order has been received and is processing'); ?>';
    var text_timeout = '<?php echo $this->__('Fahasa is processing your order, please wait a moment and try again to get result'); ?>';
    var is_confirm_shipping_addres = <?php echo Mage::getStoreConfig('eventcart_config/config/show_confirm_shipping_address')?'true':'false'; ?>;
    var orderqueue = new OrderQueue();
    orderqueue.initOrderQueue('<?php echo $this->getCheckoutUrl()."isAjax/queue"; ?>','<?php echo $this->getUrl('onestepcheckout/index/checkOrderStatus', array('_secure' => true)) ?>');
    function showloginbox() {
        var url = '<?php echo $this->getUrl('onestepcheckout/index/show_login', array('_secure' => true)); ?>';
        showLogin(url);
    }

    function showforgotpwd() {
        var url = '<?php echo $this->getUrl('onestepcheckout/index/show_password', array('_secure' => true)); ?>';
        showpwdbox(url);
    }

    function showPasswordForm() {
        $('onestepcheckout-login').hide();
        $('onestepcheckout-forgot-password').show();
    }

    function showloginform() {
        $('onestepcheckout-forgot-password').hide();
        $('onestepcheckout-login').show();
    }

    function submitLoginForm() {
        var login_validator = new Validation('onestepcheckout-login-form');
        if (login_validator.validate()) {
            showLoginLoading();
            var url = '<?php echo $this->getUrl('onestepcheckout/index/loginPost', array('_secure' => true)) ?>';
            var email = $('osclogin:email_address').value;
            var password = $('osclogin:password').value;
            var parameters = {email: email, password: password};
            var loginRequest = new Ajax.Request(url, {
                parameters: parameters,
                onComplete: loginProcess.bindAsEventListener(this),
                onFailure: ""
            });
        }
    }

    function retrievePassword() {
        var passwordValidator = new Validation('osc-forgotpassword-form');
        if (passwordValidator.validate()) {
            showPassLoading();
            var url = '<?php echo $this->getUrl('onestepcheckout/index/retrievePassword', array('_secure' => true)) ?>';
            var email = $('forgotpassword_email_address').value;
            var parameters = {email: email};
            var loginRequest = new Ajax.Request(url, {
                parameters: parameters,
                onComplete: passwordProcess.bindAsEventListener(this),
                onFailure: ""
            });
        }
    }


<?php $storeId = Mage::app()->getStore(true)->getStoreId() ?>
    var save_address_url = '<?php echo $this->getUrl('onestepcheckout/index/saveAddressOnestepcheckout', array('_secure' => true)) ?>';
    var update_address_shipping = '<?php echo Mage::getStoreConfig('onestepcheckout/ajax_update/address_shipping', $storeId) ?>';
    var update_address_payment = '<?php echo Mage::getStoreConfig('onestepcheckout/ajax_update/address_payment', $storeId) ?>';
    var update_address_review = '<?php echo Mage::getStoreConfig('onestepcheckout/ajax_update/address_review', $storeId) ?>';
    var update_shipping_payment = '<?php echo Mage::getStoreConfig('onestepcheckout/ajax_update/shipping_payment', $storeId) ?>';
    var update_shipping_review = '<?php echo Mage::getStoreConfig('onestepcheckout/ajax_update/shipping_review', $storeId) ?>';
    var update_payment_review = '<?php echo Mage::getStoreConfig('onestepcheckout/ajax_update/payment_review', $storeId) ?>';
    var city_Json = <?php echo Mage::helper('vietnamshipping')->getCityJson() ?>;
    var ward_Json = <?php echo Mage::helper('vietnamshipping')->getWardJson() ?>;
    var save_ward_url = '<?php echo $this->getUrl('onestepcheckout/index/updateWard', array('_secure' => true)) ?>';
    var region_id = '';
    var express_checked = false;
    var updated_express = true;
<?php if (Mage::getStoreConfig('onestepcheckout/ajax_update/enable_ajax', $storeId)): ?>

        //save address when change country field
    <?php if ($this->isAjaxBillingField('country')): ?>
                //2014.18.11 fix VAT apply start
        	if ($('billing:taxvat'))
                    Event.observe('billing:taxvat', 'change', function() {
                    //check empty fields
                    var empty = checkEmptyFields($('billing-new-address-form'));
                    if (empty == false || reload_payment == 2)
                        save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                    });
                //2014.18.11 fix VAT apply end
                
                //save billing when country is changed
                if ($('billing:country_id'))
                    Event.observe('billing:country_id', 'change', function() {
//                        var br = "billing\\:region_id";
//                        sortDropDownListByText(br);
                        //check empty fields
                        var empty = checkEmptyFields($('billing-new-address-form'));
                        if (empty == false || reload_payment == 2)
                            save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                        //Thinhnd
        <?php if (Mage::getStoreConfig('onestepcheckout/field_require_management/region')): ?>
                                if ($('billing:region').style.display != 'none')
                                {
                                    $('billing:region').addClassName('required-entry');
//                                    $$('span.required')[8].style.display = '';
                                }
        <?php endif; ?>
                        //end
                    });
        <?php if ($this->isShowShippingAddress()): ?>
                        if ($('shipping:country_id'))
                            Event.observe('shipping:country_id', 'change', function() {
//                                var sr = "shipping\\:region_id";
//                                sortDropDownListByText(sr);
                                //check empty fields
                                var empty = checkEmptyFields($('shipping-new-address-form'));
                                if (empty == false || reload_payment == 2)
                                    save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                            });
        <?php endif; ?>
    <?php endif; ?>

            //save address when change state/region field
    <?php if ($this->isAjaxBillingField('state/region')): ?>
                //save billing when state / region is changed
                if ($('billing:region_id'))
                    Event.observe('billing:region_id', 'change', function() {
//                        var bc = "billing\\:city_id";
//                        sortDropDownListByText(bc);
                        //check empty fields
                        var empty = checkEmptyFields($('billing-new-address-form'));
                        if (empty == false || reload_payment == 2)
                            save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                    });
                if ($('billing:region'))
                    Event.observe('billing:region', 'change', function() {
                        //check empty fields
                        var empty = checkEmptyFields($('billing-new-address-form'));
                        if (empty == false || reload_payment == 2)
                            save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                    });
        <?php if ($this->isShowShippingAddress()): ?>
                        if ($('shipping:region_id'))
                            Event.observe('shipping:region_id', 'change', function() {
//                                var sc = "shipping\\:city_id";
//                                sortDropDownListByText(sc);
                                //check empty fields
                                var empty = checkEmptyFields($('shipping-new-address-form'));
                                if (empty == false || reload_payment == 2)
                                    save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                            });
                        if ($('shipping:region'))
                            Event.observe('shipping:region', 'change', function() {
                                //check empty fields
                                var empty = checkEmptyFields($('shipping-new-address-form'));
                                if (empty == false || reload_payment == 2)
                                    save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                            });
        <?php endif; ?>
    <?php endif; ?>

    <?php if ($this->isAjaxBillingField('city')): ?>
                //save billing when state / region is changed
                if ($('billing:city_id'))
                    Event.observe('billing:city_id', 'change', function() {
                        //check empty fields
			var sIndex = $('billing:city_id').selectedIndex;
			$('billing:city').value = $('billing:city_id').options[sIndex].value;
                        var empty = checkEmptyFields($('billing-new-address-form'));
                        if (empty == false || reload_payment == 2)
                            save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                    });
                if ($('billing:city'))
                    Event.observe('billing:city', 'change', function() {
                        //check empty fields
                        var empty = checkEmptyFields($('billing-new-address-form'));
                        if (empty == false || reload_payment == 2)
                            save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                    });
        <?php if ($this->isShowShippingAddress()): ?>
                        if ($('shipping:city_id'))
                            Event.observe('shipping:city_id', 'change', function() {
                                //check empty fields
				var sIndex = $('shipping:city_id').selectedIndex;
				$('shipping:city').value = $('shipping:city_id').options[sIndex].value;
                                var empty = checkEmptyFields($('shipping-new-address-form'));
                                if (empty == false || reload_payment == 2)
                                    save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                            });
                        if ($('shipping:city'))
                            Event.observe('shipping:city', 'change', function() {
                                //check empty fields
                                var empty = checkEmptyFields($('shipping-new-address-form'));
                                if (empty == false || reload_payment == 2)
                                    save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                            });
        <?php endif; ?>
    <?php endif; ?>

            //save address when change postcode field
    <?php if ($this->isAjaxBillingField('postcode')): ?>
                //save billing when postcode is changed
                if ($('billing:postcode'))
                    Event.observe('billing:postcode', 'change', function() {
                        //check empty fields
                        var empty = checkEmptyFields($('billing-new-address-form'));
                        if (empty == false || reload_payment == 2)
                            save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                    });
        <?php if ($this->isShowShippingAddress()): ?>
                        if ($('shipping:postcode'))
                            Event.observe('shipping:postcode', 'change', function() {
                                //check empty fields
                                var empty = checkEmptyFields($('shipping-new-address-form'));
                                if (empty == false || reload_payment == 2)
                                    save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                            });
        <?php endif; ?>
    <?php endif; ?>

            //save address when change city field
    <?php if ($this->isAjaxBillingField('city')): ?>
                //save billing when city is changed
                if ($('billing:city'))
                    Event.observe('billing:city', 'change', function() {
                        //check empty fields
                        var empty = checkEmptyFields($('billing-new-address-form'));
                        if (empty == false || reload_payment == 2)
                            save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                    });
        <?php if ($this->isShowShippingAddress()): ?>
                        if ($('shipping:city'))
                            Event.observe('shipping:city', 'change', function() {
                                //check empty fields
                                var empty = checkEmptyFields($('shipping-new-address-form'));
                                if (empty == false || reload_payment == 2)
                                    save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                            });
        <?php endif; ?>
    <?php endif; ?>
            //save address when change ward field
    <?php if ($this->isAjaxBillingField('ward')): ?>
                //save billing when ward is changed
                if ($('billing:ward'))
                    Event.observe('billing:ward', 'change', function() {
                        //check empty fields
                        var empty = checkEmptyFields($('billing-new-address-form'));
                        if (empty == false || reload_payment == 2)
                            save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                    });
        <?php if ($this->isShowShippingAddress()): ?>
                        if ($('shipping:ward'))
                            Event.observe('shipping:ward', 'change', function() {
                                //check empty fields
                                var empty = checkEmptyFields($('shipping-new-address-form'));
                                if (empty == false || reload_payment == 2)
                                    save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
                            });
        <?php endif; ?>
    <?php endif; ?>
        
        //2014.18.11 delete reload when change telephone
<?php endif ?>

    //document.observe('dom:loaded', function() {
    //fix for IE9
    Event.observe(window, 'load', function() {
        if($('create_account_checkbox_id')){
            if ($('create_account_checkbox_id').checked)
                $('password_section_id').show();
            else
                $('password_section_id').hide();
        }
        if ($RF(form, 'payment[method]') != null) {
            var payment_method = $RF(form, 'payment[method]');
            if ($('container_payment_method_' + payment_method)) {
                $('container_payment_method_' + payment_method).show();
            }
            if ($('payment_form_' + payment_method)) {
                $('payment_form_' + payment_method).show();
            }
        }
    });

    function disable_payment() {
        var options = document.getElementsByName('payment[method]');
        for (var i = 0; i < options.length; i++) {
            if (!$(options[i].id).checked) {
                var container = options[i].id.replace('p_method', 'container_payment_method');
                if ($(container)) {
                    $(container).innerHTML = '';
                }
            }
        }
    }
    
    /* isUseAmazon() return true if use Amazon payment method */
	function isUseAmazon(){
		var options = document.getElementsByName('payment[method]');
		var pay = true;
		for(var i=0;i<options.length;i++){
			if($(options[i].id).checked){
				if(options[i].value == 'amazon_payments')
				pay = false;
				break;
			}
		}
		if(pay==true){
			return false;
		}
		return true;
	}
	/* end */
        
    function checkpayment() {
        var options = document.getElementsByName('payment[method]');
        var pay = true;
        for (var i = 0; i < options.length; i++) {
            if ($(options[i].id).checked) {
                pay = false;
                break;
            }
        }
        if (pay == true) {
            return false;
        }
        return true;
    }
    
    $jq(document).ready(function() {
        jQuery("#duplicated-order-pass").click(function(){
            jQuery("#pass-duplicated-order").val(true);
            jQuery('#duplicated-order').hide();
            jQuery(".duplicated-order-cover").fadeOut();
        });
        
        jQuery("#duplicated-item-pass").click(function(){
            jQuery("#pass-duplicated-item").val(true);
            jQuery('#duplicated-item').hide();
            jQuery(".duplicated-order-cover").fadeOut();
            oscPlaceOrder(this);
        });
        
        // check uplicated order
        new Ajax.Request(
            '<?php echo $this->getUrl('onestepcheckout/index/duplicatedOrder', array('_secure' => true)) ?>', {
                method: 'post',
                onLoading: function () {
                    jQuery('.youama-ajaxlogin-loader').fadeIn();
                },
                onLoaded: function () {
                    jQuery('.youama-ajaxlogin-loader').fadeOut();
                },
                onFailure: function (request, status, error) {
                    alert(request.statusText);
                },
                onSuccess: function (transport) {
                    if (200 == transport.status) {
                        var orderItems = JSON.parse(transport.responseText);
                        if(Object.keys(orderItems).length == 0){
                            jQuery("#pass-duplicated-order").val(true);
                        }else{
                            
                            var html = "";
                            for(var k in orderItems){
                                var item = orderItems[k];
                                html +=
                                    "<tr>" 
                                        + "<td>"
                                            +"<div class='col-sm-12 col-md-12 col-sms-12'>"
                                                +"<div class='col-md-5 col-sm-5 col-sms-4' style='text-align:center;'>"
                                                    +"<img style='max-width: 100px;' src='<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($image); ?>" + item["data"]["img"]+ "'>"
                                                +"</div>"
                                                +"<div class='col-md-7 col-sm-7 col-sms-8'>"
                                                    +"<div class='col-md-12 col-sm-12 col-sms-12'>"
                                                        +"<h3 class='product-name'>" + item["data"]["name"]+ "</h3>"
                                                    +"</div>";
                                                    for(var i = 0; i< item['item'].length;i++){
                                                        var itemOrder =  item['item'][i];
                                                        html +=
                                                            "<div class='col-md-12 col-sm-12 col-sms-12 order-item'>"
                                                                +"<h4> <a href='<?php echo Mage::getBaseUrl(); ?>sales/order/view/order_id/" + itemOrder["orderId"]+ "' target='_blank'>#" + itemOrder["orderId"]+ " - " + itemOrder["orderStatus"] + "</a></h4>"
                                                            +"</div>";
                                                    }
                                            html +=
                                                "</div>"
                                            +"</div>"
                                        +"</td>"
                                    + "</tr>";
                            }
                            jQuery('#duplicated-order table').html(html);
                            jQuery(".duplicated-order-cover").fadeIn();
                            jQuery('#duplicated-order').fadeIn();
                            return true;
                        }
                    }
                }
            }
        );
        
        // check uplicated item
        new Ajax.Request(
            '<?php echo $this->getUrl('onestepcheckout/index/duplicatedItem', array('_secure' => true)) ?>', {
                method: 'post',
                onLoading: function () {
                    jQuery('.youama-ajaxlogin-loader').fadeIn();
                },
                onLoaded: function () {
                    jQuery('.youama-ajaxlogin-loader').fadeOut();
                },
                onFailure: function (request, status, error) {
                    alert(request.statusText);
                },
                onSuccess: function (transport) {
                    var duplicatedItem = transport.responseText;
                    
                    // have qty = 2 in cart
                    if(duplicatedItem == 1){
                        jQuery("#pass-duplicated-item").val(false);
                    }else{
                        jQuery("#pass-duplicated-item").val(true);
                    }
                }
            }
        );
    });
    
    function oscPlaceOrder(element) {
        console.log('osc place order');
	
        // duplicated order
        var checkDuplicatedOrder = jQuery("#pass-duplicated-order").val();
        if(checkDuplicatedOrder == "false"){
            jQuery('#duplicated-order').show();
            return false;
        }
        
        // duplicated item
        var checkDuplicatedItem = jQuery("#pass-duplicated-item").val();
        if(checkDuplicatedItem == "false"){
            jQuery(".duplicated-order-cover").fadeIn();
            jQuery('#duplicated-item').fadeIn();
            return false;
        }
	
        var validator = new Validation('one-step-checkout-form');
        var form = $('one-step-checkout-form');
        if (validator.validate()) {
             if (!checkInvalidEmail()){
                jQuery("html, body").animate({ scrollTop: jQuery("#billing:email").scrollTop() }, 10);
                return;
            }
	    if(!checkWard()){
		return false;
	    }
	    <?php if(Mage::getStoreConfig('eventcart_config/config/show_confirm_shipping_address')):?>
	    if(is_confirm_shipping_addres){
		syn_confirm_shipping_address();
		$jq('.youama-ajaxlogin-cover').fadeIn();
		$jq('#popup_fahasa_shipping_confirm').fadeIn();
		return false;
	    }
	    <?php endif;?>
            if (($('p_method_hosted_pro') && $('p_method_hosted_pro').checked) || ($('p_method_payflow_advanced') && $('p_method_payflow_advanced').checked)) {
                $('onestepcheckout-place-order-loading').show();
                $('onestepcheckout-button-place-order').removeClassName('onestepcheckout-btn-checkout');
                $('onestepcheckout-button-place-order').addClassName('place-order-loader');
                $('ajaxcart-load-ajax').show();
                checkAjax('<?php echo $this->getUrl('onestepcheckout/index/saveOrderPro', array('_secure' => true)); ?>');
            } else {
                if (checkpayment()) {
                    element.disabled = true;
                    var already_placing_order = true;
                    disable_payment();
                    $('onestepcheckout-place-order-loading').show();
                    $('onestepcheckout-button-place-order').removeClassName('onestepcheckout-btn-checkout');
                    $('onestepcheckout-button-place-order').addClassName('place-order-loader');
                    //$('one-step-checkout-form').submit();
                    var options = document.getElementsByName('payment[method]');
                    for (var i = 0; i < options.length; i++) {
                        if ($(options[i].id).checked) {
                            if (options[i].id.indexOf("tco") != -1) {
                                var params = Form.serialize('one-step-checkout-form');
                                var request = new Ajax.Request(
                                '<?php echo $this->getCheckoutUrl() . 'isAjax/tco'; ?>',
                                {
                                    method: 'post',
                                    onComplete: this.onComplete,
                                    onSuccess: function(transport) {
                                        if (transport.status == 200) {
                                            if (transport.responseText.isJSON) {
                                                var response = JSON.parse(transport.responseText);
                                                $('onestepcheckout-place-order-loading').style.display = 'none';
                                                $('checkout-' + response.update_section.name + '-load').update(response.update_section.html);
                                                $('onestepcheckout-button-place-order').removeAttribute('onclick');
                                                $('onestepcheckout-button-place-order').observe('click', formsubmit());
                                                $('onestepcheckout-button-place-order').disabled = false;
                                            }
                                        }
                                    },
                                    onFailure: '', //checkout.ajaxFailure.bind(checkout),
                                    parameters: params
                                });
                            } 
							else if (options[i].id.indexOf("wirecard") != -1) {
                                var params = Form.serialize('one-step-checkout-form');
                                var request = new Ajax.Request(
                                '<?php echo $this->getCheckoutUrl() . 'isAjax/wirecard'; ?>',
                                {
                                    method: 'post',
                                    onComplete: this.onComplete,
                                    onSuccess: function(transport) {
                                        var response = JSON.parse(transport.responseText);
                                        if (response.url) {
                                            window.location.href = response.url;
                                        } else {
                                            var payment_method = $RF(form, 'payment[method]');
                                            var wireparams = {'paymentMethod': payment_method};
                                            url = '<?php echo Mage::getBaseUrl() . 'wirecard_checkout_page/processing/wirecard_checkout_pagecheckout/'; ?>';
                                            var wirerequest = new Ajax.Request(
                                            qmoreIsIframe,
                                            {
                                                method: 'get',
                                                parameters: wireparams,
                                                onSuccess: function(innerTransport) {
                                                    if (innerTransport && innerTransport.responseText) {
                                                        try {
                                                            var innerResponse = eval('(' + innerTransport.responseText + ')');
                                                        }
                                                        catch (e) {
                                                            innerResponse = {};
                                                        }
                                                        if (innerResponse.isIframe)
                                                        {
                                                            toggleQMoreIFrame();
                                                            $('qmore-iframe').src = url;
                                                        } else {
                                                            window.location.href = url;
                                                        }
                                                    }
                                                },
                                                onFailure: ''
                                            });
                                        }
                                    },
                                    onFailure: '', //checkout.ajaxFailure.bind(checkout),
                                    parameters: params
                                });
                            } 
							else {
                                if(isUseAmazon() == false){
				    jQuery(".duplicated-order-cover").fadeOut();
				    jQuery('.youama-ajaxlogin-loader').fadeOut();
				    orderqueue.submitPurchase();
                                    //$('one-step-checkout-form').submit();
								}
								else{ 
								<?php 
									if(Mage::helper('core')->isModuleEnabled('Amazon_Payments')){
										$helperAmz = new Amazon_Payments_Helper_Data();
										if(isset($helperAmz))
											$checkoutUrl = $helperAmz->getCheckoutUrl(false);
									}
								?>
									window.location.href = "<?php if(isset($checkoutUrl)) echo $checkoutUrl;?>";
								}
                            }
                            break;
                        }
                    }
                }
            }
        }
    }
//    }
    function checkWard(){
	var result = true;
	var ck_different_shipping = $('shipping:different_shipping');
	if(!$('billing-address-select') || !$('shipping-address-select')){
	    return result;
	}
	var bIndex = $('billing-address-select').selectedIndex;
	var billing_address_id = $('billing-address-select').options[bIndex].value;
	var sIndex = $('shipping-address-select').selectedIndex;
	var shipping_address_id = $('shipping-address-select').options[sIndex].value;

	if(ck_different_shipping != null){
	    if(!$('shipping:different_shipping').checked){
		if((billing_address_id != '<?php echo $this->__('New Address')?>') && (billing_address_id)){
		    for (customer_address_index in billing_customer_address_list) {
			customer_address = billing_customer_address_list[customer_address_index];
			if(billing_address_id == customer_address.value){
			    if(customer_address.hasWard == 'true'){
				return result;
			    }
			}
		    }
		    $('ward_id_update').setAttribute("address_id",billing_address_id);
		    showWard();
		    result = false;
		}
	    }
	    else{
		if((shipping_address_id != '<?php echo $this->__('New Address')?>') && (shipping_address_id)){
		    for (customer_address_index in billing_customer_address_list) {
			customer_address = billing_customer_address_list[customer_address_index];
			if(shipping_address_id == customer_address.value){
			    if(customer_address.hasWard == 'true'){
				return result;
			    }
			}
		    }
		    $('ward_id_update').setAttribute("address_id",shipping_address_id);
		    showWard();
		    result = false;
		}
	    }
	}
	return result;
    }
    
    function showWard(){
	var ward_id_update_select = $('ward_id_update');
	var city_id_update_select = $('city_id_update');
	var address_id = ward_id_update_select.getAttribute('address_id');
	$('onestepcheckout-button-place-order').removeClassName('onestepcheckout-btn-checkout');
	$('onestepcheckout-button-place-order').addClassName('place-order-loader');
	$('onestepcheckout-button-place-order').disabled = true;
	var city_name = "";
	var validate_city = false;
	var city_code = "";
	
	for (customer_address_index in billing_customer_address_list) {
	    customer_address = billing_customer_address_list[customer_address_index];
	    if(address_id == customer_address.value){
		region_id = customer_address.region_id;
		city_name = customer_address.city;
		break;
	    }
	}
	city_id_update_select.options.length = 1;
	for (city_index in city_Json[region_id]) {
		var city = city_Json[region_id][city_index];
		var option = document.createElement('OPTION');
		option.value = city.name;
		option.text = city.name.stripTags();
		option.title = city.name;
		if(city_name == city.name){
		    option.selected = true;
		    city_code = city.code;
		}
		city_id_update_select.options.add(option);
	}
	if(city_code){
	    $('update-city-content-select').style.display = "none";
	}
	else{
	    $('update-city-content-select').style.display = "";

	}
	
	
	ward_id_update_select.options.length = 1;
	for (ward_index in ward_Json[city_code]) {
		var ward = ward_Json[city_code][ward_index];
		var option = document.createElement('OPTION');
		option.value = ward.name;
		option.text = ward.name.stripTags();
		option.title = ward.name;
		ward_id_update_select.options.add(option);
	}
	$('city_update').value = "";
	$('ward_update').value = "";
	Validation.reset($('ward_id_update'));
	Validation.reset($('city_id_update'));
	jQuery(".youama-ajaxlogin-cover").fadeIn();
	jQuery('#popup-fahasa-ward').fadeIn();
    }
    
    function updateWard(){
	if($('update-city-content-select').style.display == 'none'){
	    if(!Validation.validate($('ward_id_update'))){
		return;
	    }
	}else{
	    if(!Validation.validate($('city_id_update')) || !Validation.validate($('ward_id_update'))){
		return;
	    }
	}
	var ward_name = $('ward_update').value;
	var address_id = $('ward_id_update').getAttribute('address_id');
	var city_name = '';
	if($('update-city-content-select').style.display == ''){
	    city_name = $('city_update').value;
	}
	var params = {
	    address_id: address_id,
	    ward_name: ward_name,
	    city_name: city_name
	}
	new Ajax.Request(
	save_ward_url, {
	    method: 'post',
	    parameters: params,
	    onLoading: function () {
		showLoadingAnimation();
	    },
	    onLoaded: function () {
	    },
	    onSuccess: function (result) {
		if(JSON.parse(result.responseText).success == true){
		    for (customer_address_index in billing_customer_address_list) {
			customer_address = billing_customer_address_list[customer_address_index];
			if(address_id == customer_address.value){
			    billing_customer_address_list[customer_address_index].hasWard = 'true';
			    if($('update-city-content-select').style.display == ''){
				if(JSON.parse(result.responseText).success == true){
				    express_checked = false;
				    if($('s_method_vietnamshippingexpress_vietnamshippingexpress')){
					express_checked = $('s_method_vietnamshippingexpress_vietnamshippingexpress').checked;
				    }
				    updated_express = false;
				    save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
				    jQuery(".youama-ajaxlogin-cover").fadeOut();
				    jQuery('#popup-fahasa-ward').fadeOut();
				}
			    }else{
				closeUpdateWard();
				oscPlaceOrder(document.getElementById("onestepcheckout-button-place-order"));
			    }
			    hideLoadingAnimation();
			    break;
			}
		    }
		}
	    },
	    onFailure: function (request, status, error) {
		hideLoadingAnimation();
		alert(request.statusText);
	    }
	});
    }
    
    jQuery("#city_id_update").change(function() {
	var sIndex = $('city_id_update').selectedIndex;
	$('city_update').value = $('city_id_update').options[sIndex].value;
	var city_code = "";
	for (cityId in city_Json[region_id]) {
		city = city_Json[region_id][cityId];
		if(city.name == $('city_update').value){
		    city_code = city.code;
		    break;
		}
	}
	
	var ward_id_update_select = $('ward_id_update');
	ward_id_update_select.options.length = 1;
	for (ward_index in ward_Json[city_code]) {
		var ward = ward_Json[city_code][ward_index];
		var option = document.createElement('OPTION');
		option.value = ward.name;
		option.text = ward.name.stripTags();
		option.title = ward.name;
		ward_id_update_select.options.add(option);
	}
	Validation.reset($('city_id_update'));
    });
    
    jQuery("#ward_id_update").change(function() {
	var sIndex = $('ward_id_update').selectedIndex;
	$('ward_update').value = $('ward_id_update').options[sIndex].value;
	Validation.reset($('ward_id_update'));
    });
    
    function closeUpdateWard(){
	$('onestepcheckout-button-place-order').disabled = false;
	$('onestepcheckout-button-place-order').removeClassName('place-order-loader');
	$('onestepcheckout-button-place-order').addClassName('onestepcheckout-btn-checkout');
	jQuery(".youama-ajaxlogin-cover").fadeOut();
	jQuery('#popup-fahasa-ward').fadeOut();
    }
    
    function checkAjax(url) {
        var form = $('one-step-checkout-form');
        var payment_method = $RF(form, 'payment[method]');
        var shipping_method = $RF(form, 'shipping_method');
        var parameters = {
            payment: payment_method,
            shipping_method: shipping_method
        }
        get_billing_data(parameters);
        get_shipping_data(parameters);

        if ($('giftmessage-type') && $('giftmessage-type').value != '') {
            parameters[$('giftmessage-type').name] = $('giftmessage-type').value;
        }
        if ($('create_account_checkbox_id') && $('create_account_checkbox_id').checked) {
            parameters['create_account_checkbox'] = 1;
        }
        if ($('gift-message-whole-from') && $('gift-message-whole-from').value != '') {
            parameters[$('gift-message-whole-from').name] = $('gift-message-whole-from').value;
        }
        if ($('gift-message-whole-to') && $('gift-message-whole-to').value != '') {
            parameters[$('gift-message-whole-to').name] = $('gift-message-whole-to').value;
        }
        if ($('gift-message-whole-message') && $('gift-message-whole-message').value != '') {
            parameters[$('gift-message-whole-message').name] = $('gift-message-whole-message').value;
        }
        if ($('billing-address-select') && $('billing-address-select').value != '') {
            parameters[$('billing-address-select').name] = $('billing-address-select').value;
        }
        if ($('shipping-address-select') && $('shipping-address-select').value != '') {
            parameters[$('shipping-address-select').name] = $('shipping-address-select').value;
        }

        new Ajax.Request(url, {
            method: 'post',
            evalJS: 'force',
            onSuccess: function(transport) {
                // alert(JSON.parse(transport.responseText).url);
                // Huy - Edit+add JS, CSS to display iFrame for PayPal Hosted Pro
                if (JSON.parse(transport.responseText).url == 'null' || JSON.parse(transport.responseText).url == null) {
                    $('ajaxcart-loading').style.display = 'block';
                    $('ajaxcart-loading').style.top = '10%';
                    $('ajaxcart-loading').style.left = '40%';
                    $('ajaxcart-loading').style.width = '580px';
                    $('ajaxcart-loading').style.height = '550px';
                    $('ajaxcart-loading').style.overflow = 'scroll';
                    $('ajaxcart-loading').style.padding = '5px';
                    $('ajaxcart-loading').innerHTML = JSON.parse(transport.responseText).html;
                    $('iframe-warning').style.textAlign = 'left';
                    $('hss-iframe').style.display = 'block';
                }
                else
                {
                    window.location.href = JSON.parse(transport.responseText).url;
                }
            },
            onFailure: function(transport) {
            },
            parameters: parameters
        });
    }

   save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
</script>

<div id="onestepcheckout_popup_overlay" style="display: none;">&nbsp;</div>
<div id="loading-process" style="display: none;"></div>
<?php echo $this->getChildHtml('tco_iframe'); ?>
<div id="notify-email-invalid" style="display:none;">
<p style="float:left;padding-top:27px;color:#000;font-family:tahoma;margin-left:10px;"><span style="display:block;float:left;margin-right:2px;"><?php echo $this->__('Email is ') ?></span><img style="float:left;margin-right:2px;"src="<?php echo $this->getSkinUrl('images/onestepcheckout/invalidIcon.jpg'); ?>"/><?php echo $this->__(' please check it again!') ?></p>
</div>
<div id="notify-email-invalid-overlay" style="display:none;"></div>
<!-- Terms and conditions -->
<?php $_helper = Mage::helper('onestepcheckout'); ?>
<?php $width = $_helper->getTermPopupWidth() ? $_helper->getTermPopupWidth() : 482; ?>
<?php $height = $_helper->getTermPopupHeight() ? $_helper->getTermPopupHeight() : 530; ?>

<?php if ($_helper->enableTermsAndConditions()): ?>
    
    	
    <script>
        //<![CDATA[
        Event.observe(window, 'load', function() {

            var termsPopup = new Control.Modal($('onestepcheckout-toc-popup'), {
                overlayOpacity: 0.65,
                fade: true,
                fadeDuration: 0.3
            });

            $('onestepcheckout-toc-link').observe('click', function(e) {
                e.preventDefault();
                termsPopup.open();
                var controlOverlay = $('control_overlay');
                controlOverlay.style.opacity = 0.65;
				/*window.scrollTo(0, 20);*/
            });

            $$('div#onestepcheckout-toc-popup p.close a').invoke('observe', 'click', function(e) {
                e.preventDefault();
                termsPopup.close();
            });

        });
		
		Event.observe(window, 'scroll', function() {
			var toc_popup = $('onestepcheckout-toc-popup');
			if(toc_popup){
				var toc_popup_height = toc_popup.clientHeight;
				var window_height = window.innerHeight;
				var document_height =  document.documentElement.clientHeight;
				if(typeof(window_height) == 'undefined'){
					window_height = document_height;
				}
				if(toc_popup_height <= window_height){
					toc_popup.addClassName('fix-possition-toc-popup');
				}else{
					toc_popup.removeClassName('fix-possition-toc-popup');
				}
			}
 
        });
		
        //]]>
    </script>
<?php endif; ?>
<?php if (Mage::getStoreConfig('onestepcheckout/general/suggest_address', Mage::app()->getStore()->getStoreId())): ?>
    <script type="text/javascript">
        function fillAddress(type, street, ward, city, region_id, region, country, postal_code, sublocality) {
            if (street) {
                document.getElementById(type + ':street1').value = street;
            } else {
                document.getElementById(type + ':street1').value = '';
            }
            if (sublocality){
                document.getElementById(type + ':street2').value = sublocality;
			}else{
				document.getElementById(type + ':street2').value = '';
			}
            if (ward){
                document.getElementById(type + ':ward').value = ward;
			}else{
				document.getElementById(type + ':ward').value = '';
			}
            if (city){
                document.getElementById(type + ':city').value = city;
			}else{
				document.getElementById(type + ':city').value = '';
			}
            if (country)
                document.getElementById(type + ':country_id').value = country;
            if (type == 'billing')
                billingRegionUpdater.update();
            if (type == 'shipping')
                shippingRegionUpdater.update();
			if (region){
                document.getElementById(type + ':region').value = region;
			}else{
				document.getElementById(type + ':region').value = '';
			}
            if (postal_code){
                document.getElementById(type + ':postcode').value = postal_code;
			}else{
				document.getElementById(type + ':postcode').value = '';
			}
            var params = {country: country, region_id: region_id};
            var request = new Ajax.Request(
            '<?php echo $this->getUrl('onestepcheckout/index/getreionid'); ?>',
            {
                method: 'post',
                onSuccess: function(transport) {
                    if (transport.status == 200) {
                        var id = JSON.parse(transport.responseText).id;
                        if (region_id){
                            document.getElementById(type + ':region_id').value = id;
						}else{
							document.getElementById(type + ':region_id').value = '';
						}
                        if (street) {
                            document.getElementById(type + ':street1').value = street;
                        } else {
                            //document.getElementById(type + ':street1').value = '';
                        }
                    }
                },
				onComplete: function(transport){
					save_address_information(save_address_url, update_address_shipping, update_address_payment, update_address_review);
				},
                onFailure: '',
                parameters: params
            });
        }
    </script>
<?php endif; ?>
<script type="text/javascript">
    var invalidEmailPopup = new Control.Modal($('notify-email-invalid'), {
                overlayOpacity: 0.65,
                fade: true,
                fadeDuration: 0.3
    });

    function check_valid_email(transport) {
        var response = getResponseText(transport);
        var message = response.message;
        if (message == 'valid') {
            $('email-error-message').update('');
            $('valid_email_address_image').show();
            $('onestepcheckout-button-place-order').disabled = false;
            $('onestepcheckout-button-place-order').addClassName('onestepcheckout-btn-checkout');
            $('onestepcheckout-button-place-order').removeClassName('place-order-loader');
            if($('emailvalid'))
            $('emailvalid').value = 'valid';
			invalidEmailPopup.close();

        }
        else if (message == 'invalid') {
//            $('valid_email_address_image').hide();
            $('email-error-message').update('<?php echo $this->__('<p class="e-msg">Email không hợp lệ</p>') ?>');
//            $('onestepcheckout-button-place-order').disabled = true;
//            $('onestepcheckout-button-place-order').removeClassName('onestepcheckout-btn-checkout');
//            $('onestepcheckout-button-place-order').addClassName('place-order-loader');
//            if($('emailvalid'))
//            $('emailvalid').value = 'invalid';
            //invalidEmailPopup.open();

        }
        else if (message == 'exists') {
            if($('emailvalid'))
                    $('emailvalid').value = 'valid';
            $('valid_email_address_image').hide();
            if (show_login_link)
                $('email-error-message').update('<?php echo $this->__('<p>Email của bạn đã được đăng ký. Vui lòng <a class="e-msg" href="" onclick="triggerLogin(); return false;">đăng nhập</a> để việc thanh toán dễ dàng hơn</p>')?>');
            else {
                $('email-error-message').update('<?php echo $this->__('<p>Email address already registered. Please use another email address.</p>') ?>');
            }
        }
    }

</script>

<!-- Start: Added by Daniel - 02/04/2015 - js for minicart after login -->
<script type="text/javascript">
/*
decorateList('cart-sidebar', 'none-recursive');

var minicartOptions  = {
	formKey:   "<?php echo Mage::getSingleton('core/session')->getFormKey();?>"
}
var Mini = new Minicart(minicartOptions);
Mini.init();
*/
var minicartJS = function(){
	var minicartLinks = $$('.skip-cart');
	if(minicartLinks.length > 0){
		minicartLinks.each(function(el){
				Event.observe(el,'click',function(){
					if($('header-cart') && $('header-cart').hasClassName('skip-active')){
						$('header-cart').removeClassName('skip-active');
						el.removeClassName('skip-active');
					}else{
						$('header-cart').addClassName('skip-active');
						el.addClassName('skip-active');
					}		
				});
		});
	}
	var minicartCloseLinks = $$('.skip-link-close');
	if(minicartCloseLinks.length > 0){
		minicartCloseLinks.each(function(el){
				Event.observe(el,'click',function(){
					if($('header-cart') && $('header-cart').hasClassName('skip-active')){
						$('header-cart').removeClassName('skip-active');
					}
					if(minicartLinks.length > 0){
						minicartLinks.each(function(el){
							if(el.hasClassName('skip-active')){
								el.removeClassName('skip-active');
							}
						});
					}
				});
		});
	}
}
    
    function checkInvalidEmail(){
        var isLogin = "<?php if ($this->isCustomerLoggedIn()){echo true;}else{echo false;}?>";
        if (!isLogin){
            var email_address = $("billing:email").value;
            console.log("email " + email_address);
            if (/^([a-zA-Z0-9\.\_\-]+[a-zA-Z0-9\.\_\-]@(([a-zA-Z\-0-9\_]+\.)+[a-zA-Z]{2,}))$/.test(email_address)){
                return true;
            }
            return false;
        }
        return true;
    }

</script>
<!-- End: Added by Daniel - 02/04/2015 - js for minicart after login -->
<script type="text/javascript">
//    $jq(document).ready(function() {        
//        var r = "billing\\:region_id";
//        sortDropDownListByText(r);
//        var c = "shipping\\:region_id";
//        sortDropDownListByText(c);
//    });
    
function sortDropDownListByText(selectId) {
    var foption = $jq('#'+ selectId + ' option:first');
    var soptions = $jq('#'+ selectId + ' option:not(:first)').sort(function(a, b) {
       return a.text == b.text ? 0 : a.text < b.text ? -1 : 1
    });
    $jq('#' + selectId).html(soptions).prepend(foption);              

};

function hideLoadingAnimation() {
    $jq('.loadding_ajaxcart,#wraper_ajax,.wrapper_box').remove();
}
    
function showLoadingAnimation(){
    var loading_bg = $jq('#ajaxconfig_info button').attr('name');
    var opacity = $jq('#ajaxconfig_info button').attr('value');
    var loading_image = $jq('#ajaxconfig_info img').attr('src');
    var style_wrapper =  "position: fixed;top:0;left:0;filter: alpha(opacity=70); z-index:99999;background-color:"+loading_bg+"; width:100%;height:100%;opacity:"+opacity+"";
    var loading = '<div id ="wraper_ajax" style ="'+style_wrapper+'" ><div  class ="loadding_ajaxcart" style ="z-index:999999;position:fixed; top:50%; left:50%;"><img src="'+loading_image+'"/></div></div>';
    if($jq('#wraper_ajax').length==0) {
        $jq('body').append(loading);
    }
}
</script>
<?php if(Mage::getStoreConfig('eventcart_config/config/show_confirm_shipping_address')):?>
<script>
function syn_confirm_shipping_address(){
    try{
	let ck_different_shipping = $('shipping:different_shipping');
	let $shipping_address_confirm_content = $jq('#shipping_address_confirm_content');

	if(ck_different_shipping == null || !ck_different_shipping.checked){
	    let billing_address_id = 'New Address';
	    if($('billing-address-select')){
		let bIndex = $('billing-address-select').selectedIndex;
		billing_address_id = $('billing-address-select').options[bIndex].value;
	    }
	    if((billing_address_id != 'New Address') && (billing_address_id != 'Địa chỉ mới') && (billing_address_id)){

		for (customer_address_index in billing_customer_address_list) {
		    customer_address = billing_customer_address_list[customer_address_index];
		    if(billing_address_id == customer_address.value){
			$shipping_address_confirm_content.text(customer_address.label);
			return;
		    }
		}
	    }
	    else{
		let country = $('billing:country_id').options[$('billing:country_id').selectedIndex].text;
		let region = '';
		if($('billing:region_id').getStyle('display') === 'none'){
		    region = $('billing:region').value;
		}else{
		    region =  $('billing:region_id').options[$('billing:region_id').selectedIndex].text;
		}
		let city = $('billing:city').value;
		let ward = $('billing:ward').value;
		let street = $('billing:street1').value;
		let address = (street?street:'')
			+(ward?(", "+ward):'')
			+(city?(", "+city):'')
			+(region?(", "+region):'') 
			+(country?(", "+country):'');
		$shipping_address_confirm_content.text(address);
	    }
	}
	else{
	    let shipping_address_id = 'New Address';
	    if($('billing-address-select')){
		let sIndex = $('shipping-address-select').selectedIndex;
		shipping_address_id = $('shipping-address-select').options[sIndex].value;
	    }
	    if((shipping_address_id != 'New Address') && (shipping_address_id != 'Địa chỉ mới') && (shipping_address_id)){
		for (customer_address_index in billing_customer_address_list) {
		    customer_address = billing_customer_address_list[customer_address_index];
		    if(shipping_address_id == customer_address.value){
			$shipping_address_confirm_content.text(customer_address.label);
			return;
		    }
		}
	    }else{
		let country = $('shipping:country_id').options[$('shipping:country_id').selectedIndex].text;
		let region = '';
		if($('shipping:region_id').getStyle('display') === 'none'){
		    region = $('shipping:region').value;
		}else{
		    region =  $('shipping:region_id').options[$('shipping:region_id').selectedIndex].text;
		}
		let city = $('shipping:city').value;
		let ward = $('shipping:ward').value;
		let street = $('shipping:street1').value;
		let address = (street?street:'')
			+(ward?(", "+ward):'')
			+(city?(", "+city):'')
			+(region?(", "+region):'') 
			+(country?(", "+country):'');
		$shipping_address_confirm_content.text(address);
	    }
	}
    }catch(ex){console.log(ex.message);}
};
</script>
<?php endif;?>


