<div style="background-color: #ffffff; text-align: center;padding: 50px 20px;">
    <div style="font-size: 22px; color: #000000">
        Đơn hàng của bạn đang đuợc xử lý
    </div>
    <div style="font-size: 20px; color: #000000; margin-top: 5px;">
        Vui lòng kiểm tra giỏ hàng và lịch sử đơn hàng sau vài phút
    </div>
    <div style="margin-top: 30px;">
        <a  href="/checkout/cart" style="background-color: orange; padding: 12px 15px; color: #ffffff;font-size: 16px;font-weight: 550;border-radius: 20px;">Xem Giỏ Hàng</a>
    </div>
</div>