<div style="background-color: #ffffff; text-align: center; width: 100%;padding: 50px 30px;">
    <div class=""  style="color: #000000;font-size: 20px; font-weight: 550;">ĐƠN HÀNG CỦA BẠN ĐANG ĐƯỢC XỬ LÝ</div>
</div>
<div class="ma-loading" style="width: 100%; height: 100px;"></div>
<script type="text/javascript">
    $jq(".ma-loading").waitMe({
        effect: 'bounce',
        text: '',
        bg: 'rgba(255,255,255,0.7)',
        color: '#000',
        sizeW: '',
        sizeH: '',
        source: ''
    });
    var count = 3;
    const TIME_REQUEST = 5000;
    $jq(document).ready(function () {
        setTimeOutCheckOrder();
        ;

    });

    function checkOrderStatus() {
        console.log('check order status', count);
        if (count > 0) {
            count--;
            new Ajax.Request(
                    "<?php echo $this->getUrl('onestepcheckout/index/checkOrderStatus', array('_secure' => true)) ?>", {
                        method: 'post',

                        onLoading: function () {
                            jQuery('.youama-ajaxlogin-loader').fadeIn();
                        },
                        onLoaded: function () {
                            jQuery('.youama-ajaxlogin-loader').fadeOut();
                        },
                        onSuccess: function (transport) {
                            if (transport.status == 200) {
                                var response = JSON.parse(transport.responseText);
                                if (response.success) {
                                    if (response.isProcessed) {
                                        if (response.orderId) {
                                            window.location.href = response.redirectUrl;
                                        } else {
                                            window.location.href = '/checkout/cart';
                                        }
                                        return;
                                    }
                                }
                            }
                            setTimeOutCheckOrder();
                        }
                    });


        } else {
            window.location.href = "/onestepcheckout/index/redirectPending";
        }
    }

    function setTimeOutCheckOrder() {
        setTimeout(checkOrderStatus, TIME_REQUEST);
    }
</script>