<script type="text/javascript">
//<![CDATA[    
    fhsformkey = '<?php echo $this->getFormKey()?>';
    encodeCurrentUrl = '<?php echo $this->getEncodeCurrentUrl() ?>';
    addToCartUrl = '<?php echo $this->getAddUrl('checkout/cart/add') ?>';
    addWishlistUrl = '<?php echo $this->getAddUrl('wishlist/index/add') ?>';
    addCompareUrl = '<?php echo $this->getAddUrl('catalog/product_compare/add') ?>';
//]]>
</script>
