<?php
$identify = $this->getIdentify();
$layout = $this->getLayoutId();
$tabslider_title = $this->getTitle();

$block_content_left = json_decode($this->getData('block_content_left_data'), true);
$block_content_top = json_decode($this->getData('block_content_top_data'), true);
$block_banner = ""; // define bxslider $block_content_top slider

$_helper = $this->helper('catalog/output');
$productsOnRow = $this->getProductsOnRow();
if (!$productsOnRow) {
    $productsOnRow = 3;
}
$rows = $this->getData('number_of_row');
if (!$rows) {
    $rows = 2;
}

$tsData = $this->getData('data');
$parsedData = json_decode($tsData, true);

/* for Analytics */
$relatedProductCampaignStr = '';
try {
    if ($this->getRelatedProductCampaignStr()) {
        $relatedProductCampaignStr = '?fhs_campaign=' . $this->getRelatedProductCampaignStr();
    }
} catch (\Throwable $t){}

?>

<?php
//$mobile = Mage::helper('mobiledetect')->isMobile();        
$mobile = Mage::helper('fhsmobiledetect')->isMobile();
$item_width = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/item_width');
$renderCriteoList = $this->getData('render_criteo_list');
$criteoList = array();
?>
<?php if ($mobile): ?>
    <?php if ($this->getNDisplayOnMobile() !== "0") { ?>
        <?php $rows = 1; ?>    
        <?php
        // loop tab
        foreach ($parsedData as $key => $value) {
            foreach ($value as $k => $v) {
                ?>
                <div class="categorytab-slider m-ts-con-margin">
                <div id="container">	
                <div class="tab_container">
                <div class="cd-label">
                    <?php if($v['seeAllLink']){ echo '<a href="' . $v['seeAllLink'] . '">' ; } ?>
                    <?php
                    if($v["mobile_label"]){
                        echo $v["mobile_label"];
                    }else if($v["label"]){
                        echo $v["label"];
                    }else{
                        echo $this->__($k);
                    }                    
                    ?>
                    <?php if($v['seeAllLink']){ echo '</a>' ; } ?>
                </div>
                <div id="tab<?php echo $k . '-' . $identify; ?>" class="tab_content_<?php echo $identify; ?> swiper-container-<?php echo $identify . "-" . $k; ?>" style="overflow: hidden;"> 
                    <?php $_productCollection = $this->getTabSliderProductCollection($k, $v, 1); ?>                                
                    <?php $_columnCount = $productsOnRow; ?>
                    <div class="bxslider swiper-wrapper">	
                        <?php
                        $i = 0;
                        foreach ($_productCollection as $_product):
                            $criteoList[] = $_product->getId();
                            ?>                                
                            <?php if ($i % $rows == 0): ?>
                        <div class="swiper-slide item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                                <?php endif; ?>                                    
                                <div class="item-inner" style="position: relative">
                                    <?php
                                    // Get the Special Price
                                    $specialprice = $_product->getFinalPrice();
                                    $price = $_product->getPrice();
                                    $discountLabel = Mage::helper('discountlabel')->handleDisplayDiscountLabel($_product, true, false);
                                    echo $discountLabel;
                                    ?>
                                    <div class="ma-box-content" style="padding-left: 0px">
                                        <div class="products clearfix">
                                            <div class="product images-container">
                                                <a href="<?php echo $_product->getProductUrl().$relatedProductCampaignStr ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                                    <span class="product-image">
                                                        <img style="padding-bottom:0" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(150, 250); ?>" width="270" height="364" class="flazy" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                                    </span>									    
                                                </a>
                                            </div>
                                            <h2 class="product-name m-product-name"><a href="<?php echo $_product->getProductUrl().$relatedProductCampaignStr ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>							
                                            <div class="price-label">
                                                <div class="price-box"><div style="margin-top: 20px;" class="price-box">
                                                        <?php
                                                        $sym = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
                                                        if ($price != $specialprice) {

                                                            if ($specialprice != '') {
                                                                echo '<p class="special-price">
                                                                    <span class="price-label">Special Price</span>
                                                                    <span id="product-price-384' . $_product->getId() . '" class="price m-price-font">' . '' . number_format($specialprice, 0, ",", ".") . $sym . '</span>
                                                                    </p> ';
                                                            }
                                                            if ($price != '') {
                                                                echo '<p class="old-price bg-white"><span class="price-label">';
                                                                echo $this->__('Regular Price') . ': </span>';
                                                                echo '<span id="old-price-' . $_product->getId() . '" class="price m-price-font">' . '' . number_format($price, 0, ",", ".") . $sym . '</span></p>';
                                                            }
                                                        } else {
                                                            echo '<span id="product-price-a' . $_product->getId() . '" class="regular-price">
                                                                    <span class="price m-price-font">' . '' . $this->getPriceHtml($_product, true) . '</span>                                    
                                                                    </span>';
                                                        }
                                                        ?>
                                                    </div></div>
                                            </div>
                                        </div>							
                                    </div>	
                                </div>                                
                                <?php $i++ ?>
                                <?php if ($i % $rows == 0): ?>        
                                </div>
                            <?php endif;  ?>                                        
                        <?php endforeach ?>
                    </div>

                </div><!-- #tab1 -->
                <?php
                if ($v['seeAllLink']) { 
                   $aTagLink = $v['seeAllLink'];
                    ?>
                    <div class="tabs-xem-them">
                        <a target="_blank" href="<?php echo $this->removeSlashTrailingUrl(Mage::getBaseUrl() . $aTagLink); ?>"><img style="float: right;padding-right: 10px;margin-bottom: 15px;" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."/wysiwyg/xemthem-button1.png"; ?>" alt="" /></a>
                    </div>
                <?php } ?>
                </div> <!-- .tab_container --> 
                </div> <!-- #container -->
                </div>
                <script type="text/javascript">
                    $jq(window).load(function () {                        
                        var swiper = new Swiper('.swiper-container-<?php echo $identify . "-" . $k; ?>', {
                            slidesPerView: 'auto',
                            freeMode: true,
                            longSwipesMs: 800
                        });
                    });
                </script>
                <?php
            }
        }                    
        ?>
        <script type="text/javascript">
            $jq(window).load(function () {
                var sliderH = $jq(".tab_content_<?php echo $identify; ?> .bxslider").height();
                $jq(".tab_content_<?php echo $identify; ?> .bx-viewport").attr("style", function (i, s) {
                    sliderH = parseInt(sliderH) + 10;
                    return s + "min-height: 240px !important; height: inherit;"
                });                
            });
        </script>
    <?php } ?>
<?php else : ?>
    <div class="categorytab-slider">
        <div id="container">
            <div class="tabslider-header">
                <div class="tab-title ma-title">
                    <div class="tabslider-title"><?php
                        if ($tabslider_title) {
                            echo $tabslider_title;
                        } else {
                            echo " ";
                        }
                        ?>
                    </div>
                    <div class="tabslider-tabs">
                        <ul class="tabs tabs<?php echo '-' . $identify; ?>  tab_categorys">
                            <div class="ts-header" style="float: right;">
                                <?php
                                $i = 0;
                                // loop label tab
                                foreach ($parsedData as $key => $value) {
                                    foreach ($value as $k => $v) {
                                        ?>
                                        <li class="<?php
                                        if ($v['active']) {
                                            echo "active";
                                        }
                                        ?>" rel="tab<?php echo $k . '-' . $identify; ?>">
                                                <?php
                                                if (!$v['label']) {
                                                    echo $this->__($k);
                                                } else {
                                                    echo $v['label'];
                                                }
                                                ?>
                                        </li>
                                        <?php
                                        $i++;
                                    }
                                }
                                ?>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="tabslider-top-content" style="margin-bottom: 10px; display: inline-block">
                <?php if ($block_content_top) { ?>
                    <?php
                    foreach ($block_content_top as $block_content_item) {
                        if ($block_content_item["type"] == "slider") {
                            $block_banner = $identify . "-slider"; //$block_content_item["bxsliderClass"];
                            ?>
                            <div class = "<?php echo $block_content_item["webClass"] ?>">
                                <ul class="bxslider-<?php echo $block_banner; ?>">
                                    <?php foreach ($block_content_item["data"] as $block_content_item_data) { ?>
                                        <li>
                                            <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . $block_content_item_data["urlLink"] ?>">
                                                <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $block_content_item_data["urlWebImg"] ?>" alt="" />
                                            </a>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </div>
                        <?php } else if ($block_content_item["type"] == "grid") { ?>
                            <div class = "<?php echo $block_content_item["webClass"] ?>">
                                <?php foreach ($block_content_item["data"] as $block_content_item_data) { ?>
                                    <div class="wrapperImage col-sm-6 col-md-6 col-xs-6 fhs-no-mobile-block tabsliderImg">
                                        <div class="imageNXB tabsliderNXB">
                                            <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . $block_content_item_data["urlLink"] ?>">
                                                <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $block_content_item_data["urlWebImg"] ?>" alt="" />
                                            </a>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>
                        <?php } ?>
                    <?php } ?>
                <?php } ?>
            </div>
            <div class="tab_container">
                <?php if ($block_content_left) { ?>
                    <div class="col-lg-4 col-md-4 col-sm-0 hidden-sm" style="<?php
                    if ($block_content_left[0]['position'] == "right") {
                        echo "float:right;";
                    }
                    ?>">
                        <p class="<?php if ($block_content_left[0]['position'] == "right"){ echo 'f-grid-split-right';}else{ echo 'f-grid-split-left';} ?>"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . $block_content_left[0]['pageUrl']; ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $block_content_left[0]['urlWebImg']; ?>" alt="" /></a></p>
                        <?php // echo $block_content;       ?>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-12 fhs-partial-p" style="<?php
                    if ($block_content_left[0]['position'] !== "right") {
                        echo "float:right;";
                    }
                    ?>">
                         <?php } else { ?>
                        <div class="col-lg-12 col-md-12 col-sm-12 fhs-full-p">
                        <?php } ?>

                        <?php
                        // loop product tab
                        foreach ($parsedData as $key => $value) {
                            foreach ($value as $k => $v) {
                                ?>
                                <div id="tab<?php echo $k . '-' . $identify; ?>" class="tab_content_<?php echo $identify; ?>" style="display: none;"> 
                                    <?php $_productCollection = $this->getTabSliderProductCollection($k, $v, 0); ?>                                    
                                    <?php $_columnCount = $productsOnRow; ?>
                                    <?php if ($layout != "grid" || ($layout == "grid" && !$block_content_left)) { ?>
                                        <?php
                                        if ($layout == "grid" && !$block_content_left) {
                                            $rows = 1;
                                        }
                                        ?>
                                        <ul class="bxslider">

                                            <?php
                                            $i = 0;
                                            foreach ($_productCollection as $_product):
                                                $criteoList[] = $_product->getId();
                                                ?>                                
                                                <?php if ($i % $rows == 0): ?>
                                                    <li class="item sl-width<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                                                    <?php endif; ?>
                                                    <?php
                                                    // Get the Special Price
                                                    $specialprice = $_product->getFinalPrice();
                                                    $price = $_product->getPrice();
                                                    ?>                                
                                                    <div class="item-inner" style="position: relative">
                                                        <?php
                                                        $discountLabel = Mage::helper('discountlabel')->handleDisplayDiscountLabel($_product, true, false);
                                                        echo $discountLabel;
                                                        ?>
                                                        <div class="ma-box-content">                                                    
                                                            <div class="products clearfix">
                                                                <div class="product images-container">
                                                                    <a href="<?php echo $_product->getProductUrl().$relatedProductCampaignStr ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                                                        <span class="product-image">
                                                                            <img src="<?php echo $this->getSkinUrl('images/ring_loader.gif') ?>" data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270, 364); ?>" width="270" height="364" class="flazy" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                                                        </span>									    
                                                                    </a>
                                                                </div>

                                                            </div>
                                                            <div class="actions">
                                                                <div class="actions-inner">
                                                                    <?php echo Mage::helper('discountlabel')->displayBuyButton($_product); ?>

                                                                    <?php
                                                                    if (Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/addtowishlist') || Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/addtocompare')):
                                                                        ?>
                                                                        <ul class="add-to-links">
                                                                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                                                <?php
                                                                                if (Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/addtowishlist')):
                                                                                    ?>
                                                                                    <li><a href="<?php echo $_product->getId() ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><i class="fa fa-heart"></i><?php echo $this->__('Add to Wishlist') ?></a></li>
                                                                                <?php endif; ?>
                                                                            <?php endif; ?>
                                                                            <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                                                                <?php
                                                                                if (Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/addtocompare')):
                                                                                    ?>
                                                                                    <li><span class="separator">|</span> <a href="<?php echo $_product->getId() ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare"><i class="fa fa-retweet"></i><?php echo $this->__('Add to Compare') ?></a></li>
                                                                                <?php endif; ?>
                                                                            <?php endif; ?>

                                                                        </ul>
                                                                    <?php endif; ?>
                                                                </div>	
                                                            </div>
                                                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl().$relatedProductCampaignStr ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                                                            <div class="price-label">
                                                                <?php
                                                                $f_price = Mage::helper('discountlabel')->displayProductPrice($_product, $price, $specialprice);
                                                                if ($f_price) {
                                                                    echo $f_price;
                                                                } else {
                                                                    echo '<span id="product-price-a' . $_product->getId() . '" class="regular-price">
                                                                                <span class="price">' . $this->getPriceHtml($_product, true) . '</span>                                    
                                                                                </span>';
                                                                }
                                                                ?>
                                                            </div>
                                                            <div class="fhs-rating-container">
                                                                <?php echo $this->getFahasaSummaryHtml($_product); ?>
                                                            </div>


                                                        </div>	
                                                    </div>                                
                                                    <?php $i++ ?>
                                                    <?php if ($i % $rows == 0): ?>        
                                                    </li>
                                                <?php endif; ?>                                                
                                            <?php endforeach ?>

                                        </ul>
                                    <?php }else { ?>

                                        <ul class="carousel-inner bxslider bxslider-grid" style="display: block;">
                                            <?php
                                            $count = 4;
                                            $i = 0;
                                            foreach ($_productCollection as $_product):
                                                $criteoList[] = $_product->getId();
                                                ?>
                                                <?php if ($i % $count == 0) { ?>
                                                    <li class="fhsgrid item  first active  products-grid no-margin">
                                                        <div class="item-inner">
                                                        <?php } ?>
                                                        <?php if ($i % ($count / 2) == 0) { ?>
                                                            <div class="row products-row">
                                                            <?php } ?>
                                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 _item first product-col  ">
                                                                <div class="wrap-item">
                                                                    <div class="product-block">
                                                                        <div class="col-lg-6 col-md-6 col-sm-6 padd-l-r">
                                                                            <?php
                                                                            $discountLabel = Mage::helper('discountlabel')->handleDisplayDiscountLabel($_product, true, false);
                                                                            echo $discountLabel;
                                                                            ?>
                                                                            <div class="product-img img">
                                                                                <a href="<?php echo $_product->getProductUrl().$relatedProductCampaignStr ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                                                                    <img src="<?php echo $this->getSkinUrl('images/ring_loader.gif') ?>" data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270, 364); ?>" width="270" height="364" class="flazy" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                                                                </a>          
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-lg-6 col-md-6 col-sm-6 padd-l-r">
                                                                            <div class="fhs-rating-container">
                                                                                <?php echo $this->getFahasaSummaryHtml($_product); ?>

                                                                            </div>
                                                                            <h3 class="product-name name">
                                                                                <a href="<?php echo $_product->getProductUrl().$relatedProductCampaignStr ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                                                                            </h3>
                                                                            <div class="price-label">
                                                                                <?php
                                                                                $specialprice = $_product->getFinalPrice();
                                                                                $price = $_product->getPrice();
                                                                                $f_price = Mage::helper('discountlabel')->displayProductPrice($_product, $price, $specialprice);
                                                                                if ($f_price) {
                                                                                    echo $f_price;
                                                                                } else {
                                                                                    echo '<span id="product-price-a' . $_product->getId() . '" class="regular-price">
                                                                                                                                                    <span class="price">' . $this->getPriceHtml($_product, true) . '</span>                                    
                                                                                                                                                    </span>';
                                                                                }
                                                                                ?>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>

                                                            </div>
                                                            <?php if ($i % ($count / 2) == ($count / 2) - 1) { ?>
                                                            </div>
                                                        <?php } ?>
                                                        <?php if ($i % ($count - 1) == $count - 1) { ?>
                                                        </div>
                                                    </li>
                                                <?php } ?>
                                                <?php
                                                $i++;
                                            endforeach;
                                            ?>
                                        </ul>                            
                                    <?php } ?>

                                    <?php
                                    if ($v['seeAllLink']) {
                                        $aTagLink = $v['seeAllLink'];
                                        ?>
                                        <div class="tabs-xem-them">
                                            <a target="_blank" href="<?php echo $this->removeSlashTrailingUrl(Mage::getBaseUrl() . $aTagLink); ?>"><img style="float: right;padding-right: 10px;margin-bottom: 15px;" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."/wysiwyg/xemthem-button1.png"; ?>" alt="" /></a>
                                        </div>
                                    <?php } ?>
                                    <script type="text/javascript">
                                        $jq(document).ready(function () {
                                            <?php $idBx = '#tab' . $k . '-' . $identify . ' .bxslider'; ?>
                                            $jq("<?php echo $idBx; ?>").bxSlider(
                                                    {
                                                        pause: 0,
                                                        minSlides: 1,
                                                        maxSlides: 6,
                                                        slideWidth: <?php echo $item_width ?>,
                                                        slideMargin: 45,
                                                        infiniteLoop: false,
                                                        touchEnabled: false,
                                                        hideControlOnEnd: true,
                                                        preloadImages: 'all',
                                                        onSlideAfter: function (slide, oldIndex, newIndex) {
                                                            var currentS = $jq("<?php echo $idBx; ?>");
                                                            loadImages(currentS);
                                                        }
                                                    }
                                            );
                                            $jq(".bxslider-<?php echo $block_banner; ?>").bxSlider({
                                                //onSliderLoad: function(){ 
                                                //$jq(".bxslider-<?php echo $block_banner; ?> li").css("width", "initial");
                                                //var vport = $jq(".bxslider-<?php echo $block_banner; ?>").parent();
                                                //$jq(vport).css("height", "initial");
                                                //}
                                            });
                                        });
                                    </script>
                                </div><!-- #tab1 -->

                                <?php
                            }
                        }
                        ?>

                    </div>
                </div> <!-- .tab_container --> 
            </div> <!-- #container -->
        </div>
        <script type="text/javascript">
            $jq(window).load(function () {
                $jq(".tab_content_<?php echo $identify; ?>").hide();
                chooseActive($jq("ul.tabs-<?php echo $identify; ?> li"));
                var active = $jq("ul.tabs<?php echo '-' . $identify; ?> li.active").attr("rel");
                $jq("#" + active).show();
                loadImages($jq("#" + active + " .bxslider"));
                $jq(".tab_content_<?php echo $identify; ?> .bx-viewport").css("height", "inherit");
                $jq(".bx-wrapper").css("max-width", "inherit");
                loadImages($jq(".tab_content_<?php echo $identify; ?> .bxslider"));
                $jq("ul.tabs<?php echo '-' . $identify; ?> li").click(function () {
                    $jq("ul.tabs<?php echo '-' . $identify; ?> li").removeClass("active");
                    $jq(this).addClass("active");
                    $jq(".tab_content_<?php echo $identify; ?>").hide();
                    var activeTab = $jq(this).attr("rel");
                    $jq("#" + activeTab).fadeIn();
                    //var sliderHeight = $jq("#" + activeTab + " .bx-viewport ul.bxslider").height();
                    //$jq("#" + activeTab + " .bx-viewport").css("height", sliderHeight);
                    loadImages($jq("#" + activeTab + " .bxslider"));
                });
                $jq(".hethang").unbind('click');
                    <?php if ($block_banner): ?>
                    $jq(".bxslider-<?php echo $block_banner; ?>").bxSlider({
                        //onSliderLoad: function(){ 
                        //$jq(".bxslider-<?php echo $block_banner; ?>-container").css("height", "auto");
                        //$jq(".bxslider-<?php echo $block_banner; ?>-container .bx-viewport").css("height", "inherit");
                        //}
                    });
                    $jq(".bxslider-<?php echo $block_banner; ?>-container").css("visibility", "visible");
                    <?php endif; ?>
            });
            $jq(window).resize(function () {
                waitForFinalEvent(function () {
                    var activeTab = $jq("ul.tabs<?php echo '-' . $identify; ?> li").filter(".active").attr("rel");
                    loadImages($jq("#" + activeTab + " .bxslider"));
                }, 500, randomIntFromInterval(1, 1000));
            });
        </script>
        <?php if (false): ?>
            <script type="text/javascript" src="//static.criteo.net/js/ld/ld.js" async="true"></script>
            <script type="text/javascript">
                window.criteo_q = window.criteo_q || [];
                window.criteo_q.push(
                        {event: "setAccount", account: 34556},
                        {event: "setEmail", email: ""},
                        {event: "setSiteType", type: "<?php echo Mage::helper("fhsmarketing")->getSiteType(); ?>"},
                        {event: "viewList", item: ["<?php echo implode(",", $criteoList) ?>"]}
                );
            </script>    
        <?php endif; ?>
    <?php endif; ?>
