<?php $catalogSearchHelper = Mage::helper('catalogsearch'); ?>
<div class="panel panel-success" style="margin-top: -50px">
    <div class="panel-body">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('phieudangky_block')->toHtml() ?>
    </div>
    <div class="panel-footer">
        <form class="form-horizontal" id="phieudangky_form" method="post" action="<?php echo Mage::getUrl('phieudangky/index/post'); ?>" enctype="multipart/form-data">
            <div class="form-group form-group-lg">
                <label class="col-sm-2 control-label" ></label>
                <label class="col-sm-10" >Thông Tin Về Bạn Đọc:</label>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Họ và tên:</label>
                <div class="col-sm-10">
                    <input type="text" name="name" id="name" class="form-control" placeholder="Nguyễn Văn A" required title="Vui lòng không để trống">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" >Số điện thoại liên lạc:</label>
                <div class="col-sm-10">
                    <input type="number" name="phone" id="phone" class="form-control" placeholder="0987654321" required   title="Vui lòng không để trống">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" >Bạn biết đến Website fahasa.com từ đâu?</label>
                <div class="col-sm-10">
                    <div class="radio">
                        <label><input type="radio" name="wherefrom" value="hoisach">Hội sách TPHCM lần IX - 2016</label>
                    </div>
                    <div class="radio">
                        <label><input type="radio" name="wherefrom" value="fahasa">Bạn đã từng mua hàng trên website fahasa.com</label>
                    </div>
                    <div class="radio">
                        <label><input type="radio"name="wherefrom" value="fb">Facebook</label>
                    </div>
                    <div class="radio">
                        <label><input type="radio"name="wherefrom" value="e-newsletter">Báo mạng (dantri.com.vn, kenh14.vn, mp3.zing.vn,...)</label>
                    </div>
                    <div class="radio">
                        <label><input type="radio"name="wherefrom" value="other">Nguồn Khác</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                    <input type="email" name="email" class="form-control" id="email" placeholder="nguyenvana@yahoo.com" required  title="Vui lòng không để trống">
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-sm-2 control-label">Ghi chú:</label>
                <div class="col-sm-10">
                    <input type="text" name="note" id="note" class="form-control" placeholder="Ghi chú của bạn">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Đăng ký</button>
                </div>
            </div>
        </form>
    </div>
</div>

