<?php
$data = $this->getData();
$_item = $data['item'];
?>

<li class="item odd" style="padding: 12px 16px;">
    <a href="<?php echo (substr($_item['product_url'],0,1) == "/")?$_item['product_url']:"/".$_item['product_url']; ?>" title="<?php echo $_item['name']; ?>" class="product-image">
        <img src="<?php echo $_item['image']; ?>" style="height: 68px;"   alt="<?php echo $_item['name']; ?>"></a>
    <div class="product-details" style="flex: 2;padding-left: 4px;">
        <p class="product-name-no-ellipsis" ><a href="<?php echo (substr($_item['product_url'],0,1) == "/")?$_item['product_url']:"/".$_item['product_url']; ?>" style="font-size: 1.1em;color:#0D0E0F;"><?php echo $_item['name']; ?></a></p>
        
        <span class="price" style="font-weight: 600;"><?php echo Mage::helper('core')->currency($_item['price'], true, false); ?></span>                    
        <span> x <?php echo $_item['quantity']; ?></<span>
    </div>
</li>