<div class="input-box customer-dob">
    <div style="float: left; line-height: 30px;"><?php echo $this->__('Date of Birth') ?></div>
    <?php
    if ($this->getDate() == null) {
        $this->setDateInput('d', '<div class="dob-day" style="margin-left: 5px;">
             <input placeholder="' . $this->__('DD') . '" style="width: 60px !important; type="text" id="' . $this->getFieldId('day') . '" name="' . $this->getFieldName('day') . '" value="' . $this->getDay() . '" title="' . $this->__('Day') . '" class="input-text validate-custom" ' . $this->getFieldParams() . ' />
             
         </div>'
        );

        $this->setDateInput('m', '<div class="dob-month" style="margin-left: 5px;">
             <input placeholder="' . $this->__('MM') . '" style="width: 60px !important; type="text" id="' . $this->getFieldId('month') . '" name="' . $this->getFieldName('month') . '" value="' . $this->getMonth() . '" title="' . $this->__('Month') . '" class="input-text validate-custom" ' . $this->getFieldParams() . ' />
             
         </div>'
        );

        $this->setDateInput('y', '<div class="dob-year" style="margin-left: 5px !important; width: 0px !important;">
             <input placeholder="' . $this->__('YYYY') . '" style="width: 60px !important;" type="text" id="' . $this->getFieldId('year') . '" name="' . $this->getFieldName('year') . '" value="' . $this->getYear() . '" title="' . $this->__('Year') . '" class="input-text validate-custom" ' . $this->getFieldParams() . ' />
             
         </div>'
        );
    } else {
        $this->setDateInput('d', '<div class="dob-day">
             <h4 style="width: 60px !important; type="text" id="' . $this->getFieldId('day') . '" name="' . $this->getFieldName('day') . '"  title="' . $this->__('Day') . '" class="input-text validate-custom bod-customer" ' . $this->getFieldParams() . ' />' . $this->getDay() . '</h4>
         </div>'
        );

        $this->setDateInput('m', '<div class="dob-month" style="margin-left: 5px;">
             <h4 style="width: 60px !important; type="text" id="' . $this->getFieldId('month') . '" name="' . $this->getFieldName('month') . '"  title="' . $this->__('Month') . '" class="input-text validate-custom bod-customer" ' . $this->getFieldParams() . ' />' . $this->getMonth() . '</h4>
         </div>'
        );

        $this->setDateInput('y', '<div class="dob-year" style="margin-left: 5px !important; width: 0px !important;">
             <h4 style="width: 60px !important;" type="text" id="' . $this->getFieldId('year') . '" name="' . $this->getFieldName('year') . '"  title="' . $this->__('Year') . '" class="input-text validate-custom bod-customer" ' . $this->getFieldParams() . ' />' . $this->getYear() . '</h4>
         </div>'
        );
    }
    ?>
    <?php echo $this->getSortedDateInputs() ?>
    <div class="dob-full" style="display:none;">
        <input type="hidden" id="<?php echo $this->getFieldId('dob') ?>" name="<?php echo $this->getFieldName('dob') ?>" />
    </div>

    <div class="validation-advice" style="display:none;"></div>
</div>
<script type="text/javascript">
//<![CDATA[
    var customer_dob = new Varien.DOB('.customer-dob', <?php echo $this->isRequired() ? 'true' : 'false' ?>, '<?php echo $this->getDateFormat() ?>');
//]]>
</script>