<li class="name-edit">
    <div class="input-box">
        <input placeholder="<?php echo $this->getStoreLabel('firstname') ?>*" type="text" id="<?php echo $this->getFieldId('firstname') ?>" name="<?php echo $this->getFieldName('firstname') ?>" value="<?php echo $this->getObject()->getFirstname(); ?>" title="<?php echo $this->getStoreLabel('firstname') ?>" maxlength="255" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('firstname') ?>" <?php echo $this->getFieldParams() ?> />
    </div>
</li>

<li class="name-edit">
    <div class="input-box">
        <input placeholder="<?php echo $this->getStoreLabel('lastname') ?>*" type="text" id="<?php echo $this->getFieldId('lastname') ?>" name="<?php echo $this->getFieldName('lastname') ?>" value="<?php echo $this->getObject()->getLastname(); ?>" title="<?php echo $this->getStoreLabel('lastname') ?>" maxlength="255" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('lastname') ?>" <?php echo $this->getFieldParams() ?> />
    </div>
</li>
