<script src="https://sp.zalo.me/plugins/sdk.js"></script>


<script>
    function onsharefacebook(sharedLink) {
        var share = {
            method: "share",
            href: sharedLink
        };
        FB.ui(share, function (response) {});
    }
    window.fbAsyncInit = function () {
        FB.init({
            appId: '331898836987489',
            autoLogAppEvents: true,
            xfbml: true,
            version: 'v3.2'
        });
    };

    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {
            return;
        }
        js = d.createElement(s);
        js.id = id;
        js.src = "https://connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

<?php $post = $this->getPost(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="postWrapper" style="margin-bottom: 50px;">
    <div class="postTitle">
        <h2 style="font-size: 24px;"><?php echo $post->getTitle(); ?></h2>
        <div class="col-xs-12" style="margin-top: 10px;">
            <div class="col-md-2" style="padding-left: 5px; padding-right: 5px; width: auto;">
                <div class="blog-logo">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)."/frontend/ma_vanese/fahasa/images/logo.png"; ?>"  style="max-height: 80px; max-width:100px ;margin-top: 20px;"/>
                </div>
            </div>
            <div class="col-md-10">
                <div class="postDetails" >
                    
                    <div class="post-by" style="color: #222; padding: 5px 0px 10px 0px;">
                        <?php echo $this->__("Posted by:"); ?> <span><?php echo $post->getUser(); ?>
                        </span></div>
                    <div>
                        <span style="color: #222;"><?php echo $this->__("Created at") . ": " . $post->getCreatedTime(); ?></span>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="postContent">
        <?php echo $post->getPostContent(); ?>
    </div>
    <div class = "fhs-social-share">
        <ul class ="fhs-blog-share">
            <li class="btnZalo blue zalo-share-button" style="background-color: #018fe5; font-size: 14px;" data-href="" data-oaid="848806348654063" data-layout="icon-text" data-color="blue" data-customize="true" >
                <a href="#" title="Chia sẻ Zalo" style="color: #FFF;"><span class="ti-zalo"> </span>Chia sẻ Zalo</a>
            </li>

            <li>
                <?php $blogUrl = $post->getAddress() . "?postId=" . $post->getPostId(); ?>
                <button class="btn-fb-share" onclick="onsharefacebook(`<?php echo $blogUrl; ?>`)" title="Chia sẻ Facebook"> <span class="ti-facebook"></span>Chia sẻ Facebook </button>
            </li>
        </ul>
    </div>
    <?php echo $this->getBookmarkHtml($post) ?>

    <!--<div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>-->
</div>
<!-- Comment Section -->
<div class="blog-post-comment">
    <?php if ($this->getCommentsEnabled()): ?>
        <?php $comments = $this->getComment(); ?>
        <?php if (count($comments) > 0): ?>
            <div class="postTitle">
                <h2><?php echo $this->__('Post Comments') ?></h2>
            </div>

            <?php echo $this->getChildHtml('magentothem_blog_comments_toolbar'); ?>
            <?php foreach ($comments as $comment) : ?>
                <div class="commentWrapper">
                    <div class="commentDetails"><h4 class="username"><?php echo $comment->getUser(); ?></h4> <?php echo $this->formatDate($comment->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?></div>
                    <div class="commentContent"><?php echo nl2br($comment->getComment()); ?></div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php if ($post->getComments()): ?>
            <div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
        <?php else: ?>
            <div class="postTitle">
                <h2><?php echo Mage::helper('blog')->__('Submit Comment') ?></h2>
            </div>
            <div class="postCommnentForm">
                <?php if ($this->getLoginRequired()): ?>
                    <?php if ($this->helper('customer')->isLoggedIn()): ?>

                        <form action="" id="postComment" method="post">
                            <fieldset class="group-select">

                                <ul class="form-list">
                                    <li>

                                        <div class="input-box magentothem-blog-comment-area">
                                            <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
                                            <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" style="height:150px;width:95%;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                                        </div>
                                    </li>
                                </ul>
                            </fieldset>
                            <div class="button-set" style="width:96%">
                                <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                                <input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
                                <input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
                                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                                <button class="form-button button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                            </div>
                        </form>

                        <script type="text/javascript">
                            var contactForm = new VarienForm('postComment', false);
                        </script>

                    <?php else: ?>
                        <p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
                        <p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
                    <?php endif ?>

                <?php else: ?>

                    <form action="" id="postComment" method="post">
                        <fieldset class="group-select">

                            <ul class="form-list">
                                <li>
                                    <div class="input-box">
                                        <label for="name" class="required"><?php echo Mage::helper('blog')->__('Name') ?><em>*</em></label><br />
                                        <input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" class="required-entry input-text" type="text" />
                                    </div>

                                    <div class="input-box">
                                        <label for="email" class="required"><?php echo Mage::helper('blog')->__('Email') ?><em>*</em></label><br />
                                        <input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email" type="text" />
                                    </div>

                                    <div class="clear"></div>

                                    <div class="input-box magentothem-blog-comment-area">
                                        <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
                                        <textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text" style="height:150px;width:95%;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                                    </div>
                                </li>

                                <?php
                                if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()) {
                                    ?><li><?php
                                        require_once 'recaptcha/recaptchalib-magentothem.php';

                                        // Get a key from http://recaptcha.net/api/getkey
                                        $publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
                                        $privatekey = Mage::getStoreConfig('blog/recaptcha/privatekey');
                                        $error = null;

                                        echo recaptcha_get_html($publickey, $error);
                                        ?></li><?php
                                }
                                ?>
                            </ul>
                        </fieldset>
                        <div class="button-set" style="width:96%">
                            <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                            <button class="button form-button" type="submit"><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></button>
                        </div>
                    </form>

                    <script type="text/javascript">
                        var contactForm = new VarienForm('postComment', false);
                    </script>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</div>
<!--product slider-->
<?php  if($post->getBlockId()){
    echo "</div>";
    echo "<div class='col-main col-lg-9 col-md-9 col-sm-12 col-xs-12 col-fhs-main-body' style='margin-top: 30px;padding-bottom: 20px;float:right;'>"
	.Mage::helper('fahasa_catalog/cache')->getBlockId($post->getBlockId())
	."</div>";
}
?>
