<?php 
    $post = $this->getPost(); 
//    $TABSLIDER_SCRIPT = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS, true)
//        ."lib/tabslider.js?q="
//        .Mage::getStoreConfig('bubble_queryfier/suffix_js_css/suffix');
//    $loading_icon_url = $this->getSkinUrl('images/ring_loader.gif');
//    $tabslider_title = $this->__('Related Products');
//    $identify = $post->getIdentify();
//    $item_width = 155;
//    $rows = 1;
?>
