<div style="margin-bottom: 30px;">
    <div style="vertical-align: middle;display: flex; padding: 8px 0; background-color: white;">
        <div class="col-sm-7">
            <a target="_blank" href="https://www.facebook.com/fahasa/" title="Facebook">
                <img alt="Facebook" style="width: 30px; height: auto;" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)."frontend/ma_vanese/fahasa/images/footer/Facebook-on.png" ?>">
            </a>
            <a target="_blank" href="https://www.instagram.com/fahasa_official/" title="Instagram">
                <img alt="Instagram" style="width: 30px; height: auto;" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)."frontend/ma_vanese/fahasa/images//footer/Insta-on.png" ?>">
            </a>
            <a target="_blank" href="https://www.youtube.com/channel/UCUZcVOLSxK1q6RfgzQ9-HYQ" title="Youtube">
                <img alt="Youtube" style="width: 30px; height: auto;" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)."frontend/ma_vanese/fahasa/images//footer/Youtube-on.png" ?>">
            </a>
            <a target="_blank" href="https://www.pinterest.com/fahasaVN/" title="Pinterest">
                <img alt="Pinterest" style="width: 30px; height: auto;" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)."frontend/ma_vanese/fahasa/images//footer/pinterest-on.png" ?>">
            </a>
        </div>
        <div class="col-sm-5" style="margin-top: 7px;"><span style="font-size: 12px; font-weight: bold;"><?php echo '#fahasaOnline'; ?></span></div>
    </div>
</div>
