<?php if(Mage::getStoreConfig('seriesbook_config/config/is_active')):?>
<?php 
    $series_id= $this->getRequest()->getParam('id', '');
    $page_type= $this->getRequest()->getParam('page_type', '');
    $page_size = Mage::getStoreConfig('seriesbook_config/config/page_size');
    $sort_by = Mage::getStoreConfig('seriesbook_config/config/sort_by');
    
    $is_page_type = true;
    $is_lazy_loading = false;
    $is_grid = false;
    $block_id = rand(100000,999999);
    $blockId = $this->getData("blockId");
    $is_show_info = true;
    
    if(empty($series_id)){$series_id = $this->getData('series_id');}
    if(empty($series_id) || !is_numeric($series_id)){$series_id = 0;}
    
    $dont_show_info = $this->getData('dont_show_info');
    if(!empty($dont_show_info)){
	$is_show_info = false;
    }
    
    if(empty($page_type)){$page_type = $this->getData('page_type');}
    if($page_type == 'slider'){$is_page_type = $is_show_info = false;}
    if($page_type == 'grid'){$is_page_type = $is_show_info = false; $is_grid = true; $page_size = 10;}
    
    $is_lazy_loading_data = $this->getData('lazy_loading');
    if(!empty($is_lazy_loading_data)){
	$is_lazy_loading = $is_lazy_loading_data;
    }
    
    $sort_by_list = [
	"Episode Newest"=>"",
	"Weekly BestSeller"=>"num_orders",
	"Monthly BestSeller"=>"num_orders_month",
	"Yearly BestSeller"=>"num_orders_year",
	"Weekly Trending"=>"product_view",
	"Monthly Trending"=>"product_view_month",
	"Yearly Trending"=>"product_view_year",
	"Discount"=>"discount_percent",
	"Sale Price"=>"min_price",
	"Created At"=>"created_at",
	];
    
    $skin_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN, true);
    $queryfier = Mage::getStoreConfig('bubble_queryfier/suffix_js_css/suffix');
    $JS_SCRIPT = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS, true)."lib/seriesbook.js?q=".$queryfier;
    $CSS_FILE = $skin_url."frontend/ma_vanese/fahasa/css/seriesbook.css?q=".$queryfier;
    
    $language = [];
    $language['btn_unfollow_white'] = "<button type='button' onclick='seriesbook_page.setSeriesBookPage({{seriesbook_id}}, false);event.stopPropagation();' title='".$this->__('Unfollow')."' class='fhs-btn-view-promo-follow'><span><img src='".$skin_url.'frontend/ma_vanese/fahasa/images/ico-minus.svg?q='.$queryfier."'/></span><span>".$this->__('Unfollow')."</span></button>";
    $language['btn_unfollow'] = "<button type='button' onclick='seriesbook_page.setSeriesBookPage({{seriesbook_id}}, false);event.stopPropagation();' title='".$this->__('Unfollow')."' class='fhs-btn-view-promo-follow active'><span><img src='".$skin_url.'frontend/ma_vanese/fahasa/images/ico-minus-white.svg?q='.$queryfier."'/></span><span>".$this->__('Unfollow')."</span></button>";
    $language['btn_follow'] = "<button type='button' onclick='seriesbook_page.setSeriesBookPage({{seriesbook_id}}, true);event.stopPropagation();' title='".$this->__('Follow')."' class='fhs-btn-view-promo-follow active'><span><img src='".$skin_url.'frontend/ma_vanese/fahasa/images/ico-plus.svg?q='.$queryfier."'/></span><span>".$this->__('Follow')."</span></button>";
    $language['unfollow_white'] = "<span><img src='".$skin_url.'frontend/ma_vanese/fahasa/images/ico-minus-white.svg?q='.$queryfier."'/></span><span>".$this->__('Unfollow')."</span>";
    $language['unfollow'] = "<span><img src='".$skin_url.'frontend/ma_vanese/fahasa/images/ico-minus.svg?q='.$queryfier."'/></span><span>".$this->__('Unfollow')."</span>";
    $language['follow'] = "<span><img src='".$skin_url.'frontend/ma_vanese/fahasa/images/ico-plus.svg?q='.$queryfier."'/></span><span>".$this->__('Follow')."</span>";
    $language['publisher'] = $this->__("Publisher");
    $language['author'] = $this->__("Author");
    $language['add_to_cart'] = $this->__("Add to cart");
    $language['series_set'] = $this->__('Series set');
    $language['fail_icon'] = $this->getSkinUrl('images/logo-alert-fail.png');
    $language['cart_icon'] = $skin_url."frontend/ma_vanese/fahasa/images/ico_shoppingbag.png?q=".$queryfier;
    
    $helper = Mage::helper("seriesbook");
    $fhsCampaign = "?fhs_campaign=".$helper->getFhsCampaignSeriProduct();
?>
<link rel="stylesheet" type="text/css" href="<?php echo $CSS_FILE; ?>" media="all" />
<div <?php echo (!empty($blockId))?'id="'.$blockId.'"':''; ?> class="page-empty-banner col-lg-12 col-md-12 col-sm-12">
        <div class="col-main">
             <div class="container">
                <div class="container-inner">
<div style="justify-content: center;">
		<!-- Begin Content -->
		<div class="clear"></div>
		<div id="fhs-product-grid<?php echo $block_id;?>" class="fhs-product-grid loading">
		    <?php if($is_page_type):?>
			<div class="fhs-product-grid-title-icon series_header"><img src="<?php echo $skin_url.'frontend/ma_vanese/fahasa/images/ico_seriesbo.svg?q='.$queryfier;?>"/><span><?php echo $this->__('Series set');?></span></div>
		    <?php endif;?>
		    
		    <div id="seriesbook_grid_item_first<?php echo $block_id;?>" class="seriesbook_info"></div>
		    <div class="toolbar-top">
			<div class="toolbar  col-sm-12 col-xs-12 col-md-12 ">
			    <div id="seriesbook_info_name<?php echo $block_id;?>" class="seriesbook_info_name" <?php echo (!$is_page_type)?'style="width:100%; display: block !important;"':'';?>></div>
			    <?php if($is_page_type):?>
				<div class="sorter">
				    <p class="view-mode">
				    </p>
				    <div class="abc-xyz">
					<div class="dropdownfhs-text hidden-xs"><p><?php echo $this->__('Sort By') ?> :</p></div>
					<div class="sort-by dropdownfhs dropdownfhs-select">
					    <div class="selectBox selectBox-order selectBox-order<?php echo $block_id;?>">
						<span class="selected selected-order selected-order<?php echo $block_id;?>"></span>
						<span class="selectArrow selectArrow-order selectArrow-order<?php echo $block_id;?>"></span>
						<div class="selectOptions selectOptions-order selectOptions-order<?php echo $block_id;?>" style="display: none;">
						    <?php foreach ($sort_by_list as $sort_key => $sort_item): ?>
							<span  class="selectOption selectOption-order selectOption-order<?php echo $block_id;?>" value="<?php echo $sort_item; ?>" <?php echo ($sort_item == trim($sort_by)) ? 'selected=\"selected\"' : ''; ?>><?php echo $this->__($sort_key); ?></span>
						    <?php endforeach; ?>
						</div>
					    </div>
					</div>
				    </div> 
				</div>
			    <?php endif;?>
			</div>
		    </div>
		    <div class="clear"></div>
		    
		    <?php if($is_page_type):?>
			<div id="seriesbook_grid_item_first<?php echo $block_id;?>" class="seriesbook_first_item"></div>

			<div id="seriesbook_grid<?php echo $block_id;?>" class="fhs-product-grid-content seriesbook_grid" style="display: none;">
			    <ul id="seriesbook_grid_item<?php echo $block_id;?>" class="fhs-product-grid-list"></ul>
			</div>
			<div id="seriesbook_bottom<?php echo $block_id;?>" style="clear: both;"></div>
			<div id="seriesbook_empty<?php echo $block_id;?>" class="seriesbook_empty" style="display:none;">
			    <img width="90" height="90" src="<?php echo $skin_url."/frontend/ma_vanese/fahasa/images/checkout_cart/ico_emptycart.svg?q=".$queryfier;?>">
			    <div><?php echo $this->__("Don't have product");?></div>
			</div>
			<div class="fhs_loading_panel">
			    <img class="default-icon-loading" src="<?php echo $skin_url."/frontend/ma_vanese/fahasa/images/ring_loader.svg";?>">
			</div>
		    <?php else:?>
			<div id="seriesbook_grid<?php echo $block_id;?>" class="fhs-product-slider-content" style="display: none;">
			    <div id="seriesbook_slider<?php echo $block_id;?>" class="swiper-container">
				<ul id="seriesbook_grid_item<?php echo $block_id;?>" class="swiper-wrapper fhs-product-slider-list"></ul>
			    </div>
			    <div id="fhs-tab-slider-prev<?php echo $block_id;?>" class="fhs-tab-slider-prev position-tab-prev swiper-button-prev" ></div>
			    <div id="fhs-tab-slider-next<?php echo $block_id;?>" class="fhs-tab-slider-next position-tab-next swiper-button-next" ></div>
			    <div class="clear tabs-xem-them xem-them-item-aaa">
				<a href="/seriesbook/index/series/id/<?php echo $series_id.$fhsCampaign.'_MORE';?>"><?php echo $this->__('View more'); ?></a>
			    </div>
			</div>
			<div id="seriesbook_empty<?php echo $block_id;?>" class="seriesbook_empty" style="display:none;">
			    <img width="90" height="90" src="<?php echo $skin_url."/frontend/ma_vanese/fahasa/images/checkout_cart/ico_emptycart.svg?q=".$queryfier;?>">
			    <div><?php echo $this->__("Don't have product");?></div>
			</div>
			<div class="fhs_loading_panel">
			    <img class="default-icon-loading" src="<?php echo $skin_url."/frontend/ma_vanese/fahasa/images/ring_loader.svg";?>">
			</div>
		    <?php endif;?>
		</div>
		
		<div id="seriesbook_follow_btn<?php echo $block_id;?>"></div>
		<!-- End Content -->

		</div>
	    </div>
	</div>
    </div>
</div>


<script type="text/javascript" src="<?php echo $JS_SCRIPT; ?>"></script>
<script type="text/javascript">
    var seriesbook_page_<?php echo $block_id;?> = new SeriesBook();
    seriesbook_page_<?php echo $block_id;?>.initSeriesBookPage(<?php echo $is_page_type?'true':'false';?>, <?php echo $is_grid?'true':'false';?>, <?php echo json_encode($block_id);?>, <?php echo json_encode($language, JSON_UNESCAPED_UNICODE);?>, <?php echo json_encode($series_id);?>, <?php echo json_encode(trim($sort_by));?>, <?php echo json_encode($page_size);?>, <?php echo json_encode($fhsCampaign); ?>, <?php echo $is_lazy_loading?'true':'false';?>, <?php echo $is_show_info?'true':'false';?>);
</script>
<?php endif;?>