<li class="item odd">
    <a href="http://192.168.1.25/cho-den-mau-giao-thi-da-muon.html" title="Chờ Đến Mẫu Giáo Thì Đã Muộn" class="product-image">
        <img src="<?php echo $_item['image']; ?>" width="50" height="66" alt="Chờ Đến Mẫu Giáo Thì Đã Muộn"></a>
    <div class="product-details">
        <a href="http://192.168.1.25/checkout/cart/" title="Sửa sản phẩm" class="btn-edit">Sửa sản phẩm</a>
        <p class="product-name"><a href="http://192.168.1.25/cho-den-mau-giao-thi-da-muon.html"><?php echo $_item['name']; ?></a></p>
        <strong>1</strong> x
        <span class="price">0&nbsp;đ</span>                    
    </div>
</li>