<form id="opc-co-shipping-method-form" autocomplete="off">
    <div id="checkout-shipping-method-load">
        <?php echo $this->getChildHtml('available') ?>
    </div>
    <div class="inner-box">
        <?php             
            echo $this->getChildHtml('shipping_magikfees') 
        ?>
    </div>
    <div id="onepage-checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ?>
    </div>    
</form>