<?php 
    Mage::register('ignore_mana_config', true);
    $mobile = Mage::helper('fhsmobiledetect')->isMobile();
    $product_helper = Mage::helper('fahasa_catalog/product');
    $catalog_param = Mage::registry('catalog_param');
    
    $cat_id = $catalog_param['cat_id'];
    $filters_param = $catalog_param['filters_param'];
    $currentPage = $catalog_param['currentPage'];
    $limit = $catalog_param['limit'];
    $order = $catalog_param['order'];
    
    if(!is_numeric($limit)){$limit = 24;}else if($limit > 48){$limit = 48;}else if($limit < 12){$limit = 12;}
    if(!is_numeric($currentPage)){$currentPage = 1;}
    
    if(!empty($order)){
	if(!empty($is_series_type)){
	    if($is_series_type){
		$order = $product_helper->checkOrderBy('series', $order);
	    }else{
		$order = $product_helper->checkOrderBy('product', $order);
	    }
	}else{
	    $order = $product_helper->checkOrderBy('product', $order);
	}
    }
    
    $is_series_type = $catalog_param['is_series_type'];
    $priceSelected = $catalog_param['priceSelected'];
    $checkPriceFormat = false;
    
    $languages = Mage::helper('fahasa_catalog/product')->getLanguagesList('catalog');
    
    $CATALOG_SCRIPT = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS, true)
            ."lib/catalog.js?q="
            .Mage::getStoreConfig('bubble_queryfier/suffix_js_css/suffix');
    $default_show_limit = 8;
    
    $arrayPrice = array(
        '0' => array(
            'name' => '0đ - 150,000đ',
            'min' => 0,
            'max' => 150000,
            'value' => "0,150000"
        ),
        '1' => array(
            'name' => '150,000đ - 300,000đ',
            'min' => 150000,
            'max' => 300000,
            'value' => "150000,300000"
        ),
        '2' => array(
            'name' => '300,000đ - 500,000đ',
            'min' => 300000,
            'max' => 500000,
            'value' => "300000,500000"
        ),
        '3' => array(
            'name' => '500,000đ - 700,000đ',
            'min' => 500000,
            'max' => 700000,
            'value' => "500000,700000"
        ),
        '4' => array(
            'name' => '700,000đ - '. $this->__('above'),
            'min' => 700000,
            'max' => 9999999,
            'value' => "700000,9999999"
        )
        
    );
    $d = 'đ';
    $str = ''; // lay du lieu filter load lan dau tien qua ben product.
    try {
	$data = $product_helper->loadCatalog($cat_id, $filters_param, $limit, $currentPage, $order, $is_series_type);
	Mage::register('catalog_data', $data);
    } catch (Exception $ex) {
	Mage::log("category loading msg:".$ex->getMessage(), null, "buffet.log");
    }
    
    $filters = [];
    if($data){
	if($data['price_range']){
	    if(($data['price_range']['min'] != $data['price_range']['price_range']['min']) 
		||($data['price_range']['max'] != $data['price_range']['price_range']['max'])){
		$filters['price'] = $data['price_range']['min'] .','.$data['price_range']['max'];
	    }
	}
	foreach($data['attributes'] as $attr){
	    if(sizeof($attr['options']) <= 0){
		continue;
	    }
	    foreach ($attr['options'] as $option){
		if($option['selected']){
		    if(!$filters[$attr['code']]){
			$filters[$attr['code']] = $option['id'];
		    }else{
			$filters[$attr['code']] .= "_".$option['id'];
		    }
		}
	    }
	}
    }
    
    //cal current category
    $last_parrent_index = 0;
    $current_is_in_parrent = false;
    foreach ($data['parent_categories'] as $key=>$parent_categories){
	if($parent_categories['id'] == $data['category']['id']){
	    $current_is_in_parrent = true;
	}else{
	    $last_parrent_index = $key;
	}
    }
    $is_expand_category = false;
    $display_count = Mage::getStoreConfig('catalog/layered_navigation/display_product_count');
?>
<style type="text/css">
    .m-overlay {
	display: none;
	background: white;
	filter: alpha(opacity=0);
	-moz-opacity: 0;
	-khtml-opacity: 0;
	opacity: 0;
	left: 0px;
	top: 0px;
	width: 100%;
	height: 100%;
	float: left;
	position: fixed;
	z-index: 10000;
    }
</style>
<div class="mb-mana-catalog-leftnav">
    <div class="block block-layered-nav">
         <?php if ($mobile) : ?>
            <div class="block-title">
                <strong><span><?php echo $this->__('Shop By') ?></span></strong>
            </div>
        <?php endif; ?>
	<div class="block-content">
	    <div class="currently">
		<div class="block-subtitle ">
		    <div class="m-subtitle-actions">
			<div class="m-expand-collapse">
			    <div class="btn-expand-collapse"></div>
			</div>
		    </div>
		    <span>Currently Shopping by:</span>
		</div>
<!--BEGIN FILTERS-->
                    <?php if ($mobile) : ?>
                        <ol id='dislay_fillter_current'>
                        </ol>    
                    <?php endif; ?>
		    <?php if(sizeof($filters) > 0): ?>
			<?php foreach ($filters as $key=>$filter):?>
			<?php if($key == "price"):
			    $prices = explode(',',$filter);?>
                                <?php
                                    $str .="<li><a onclick=\"catalog_ajax.removeFilter_click('price','')\" title='".$languages['removethisitem']."' class='btn-remove'>".$languages['removethisitem']."</a><span class='label'>".$languages['price'].":  ".number_format($prices[0], 0, ".", ",")." - ".number_format($prices[1], 0, ".", ",")."</span></li>";
                                    $objCodeToDelete[] = array(
                                        'code' => $key,
                                        'attr' => ''
                                    );
                                ?>
			    <?php else: ?>
				<?php $attributes = explode('_',$filter); ?>
				<?php foreach ($attributes as $attr_id):?>
				    <?php foreach($data['attributes'] as $attr): ?>
					<?php if($attr['code'] == $key): ?>
					    <?php foreach ($attr['options'] as $option): ?>
						<?php if($option['id'] == $attr_id): ?>
                                                    <?php
                                                        $str .= "<li><a onclick=\"catalog_ajax.removeFilter_click('" . $key . "','" . $attr_id . "')\" title='" . $languages['removethisitem'] . "' class='btn-remove'>" . $languages['removethisitem'] . "</a><span class='label'>" . $attr['label'] . ": " . $option['label'] . "</span></li>";
                                                        $objCodeToDelete[] = array(
                                                            'code' => $key,
                                                            'attr' => $attr_id
                                                        );
                                                    ?>
						<?php endif; ?>
					    <?php endforeach; ?>
					<?php endif; ?>
				    <?php endforeach; ?>
				<?php endforeach; ?>
			    <?php endif; ?>
		    <?php endforeach; ?>
                    <?php if(count($objCodeToDelete) > 1) : $str .="<li class='delete-all-category'><a onclick=\"catalog_ajax.removeAllFilter_click()\"><span>Xóa tất cả</span></a></li>"; endif; ?>
		    <?php endif; ?>
                <?php if($mobile) :?><div style="clear:both;"></div><?php endif; ?>
<!--END FILTERS-->
	    </div>
<!--BEGIN CATEGORY-->
	    <div class="block-subtitle m-filter-group " data-id="left-0"></div>
	    <dl class="narrow-by-list" id="narrow-by-list-0">
		<dt class="odd" data-id="m_left_category_filter"><?php echo $this->__('Category'); ?></dt>
		<dd class="odd">
                    <ol id="parent-category" class="m-parent-category-list">
                        <?php
                        // phan loai cap trong parent_categories moi con cua no margin left +8 px;
                        $countParent_categories = count($data['parent_categories']);
                        $numberMargin = 0;$dem = 0;
                        if ($data['parent_categories']):
                        ?>
                            <?php foreach ($data['parent_categories'] as $key => $parent_categories): ?>
                                <?php if ($parent_categories['id'] != $data['category']['id']): ?>
                                    <?php
                                    if (!$current_is_in_parrent && ($last_parrent_index == $key)) {
                                        continue;
                                    }if($dem > 0){
                                        $numberMargin += 10;
                                    }
                                    ?>
                                    <li <?php if($numberMargin > 0): echo "style='margin-left: ".$numberMargin."px;'"; endif; ?> >
                                        <a href="<?php 
					echo $parent_categories['url'];
					?>" cat_id='<?php echo $parent_categories['id'];?>' onclick='catalog_ajax.category_click(this);' title="<?php echo $parent_categories['name'];?>"><?php echo $parent_categories['name'];?></a>
                                    </li>
                                <?php $dem++; endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    </ol>
                    <div id="current-category" class="m-current-category <?php if(count($data['parent_categories']) == 1) : echo 'parent-current-category'; endif;?>"
                    <?php $numberMargin+= 10; if(count($data['parent_categories']) >= 2): echo "style='margin-left:".$numberMargin."px;'"; endif; ?>>

			<?php
			if(!$current_is_in_parrent):?>
			    <a href='<?php echo $data['parent_categories'][$last_parrent_index]['url'];?>' cat_id='<?php echo $data['parent_categories'][$last_parrent_index]['id'];?>' onclick='catalog_ajax.category_click(this);' title='<?php echo $data['parent_categories'][$last_parrent_index]['name'];?>'><?php echo $data['parent_categories'][$last_parrent_index]['name'];?></a>
			<?php else: ?>
			    <?php if($data['category']):?>
				    <span class="m-selected-filter-item dfafsaf"><?php echo $data['category']['name'];?></span>
			    <?php endif; ?>
			<?php endif; ?>
		    </div>
		    <ol id="children-categories" class="m-child-category-list" style="<?php echo 'margin-left:'.$numberMargin.'px;';?>">
			<?php if($data['children_categories']):?>
			    <?php $current_cat_index = 0; foreach ($data['children_categories'] as $children_categories): ?>
				<?php if($children_categories['count'] > 0): $current_cat_index++;?>
				    <li>
					<?php if($children_categories['id'] != $data['category']['id']):?>
					<a href="<?php echo $children_categories['url'];?>" cat_id='<?php echo $children_categories['id'];?>' onclick='catalog_ajax.category_click(this);' title="<?php echo $children_categories['name'];?>"><?php echo $children_categories['name'];?></a> <?php echo $display_count?'('.$children_categories['count'].')':'';?>
					<?php else: ?>
					<?php if(!$is_expand_category && $current_cat_index > $default_show_limit){$is_expand_category = true;}$current_cat_index++;?>
					<span class='m-selected-filter-item'><?php echo $children_categories['name'];?></span> <?php echo $display_count?'('.$children_categories['count'].')':'';?>
					<?php endif; ?>
				    </li>
				<?php endif; ?>
			    <?php endforeach; ?>
			<?php endif; ?>
		    </ol>
		    <div class="m-more-less" id="m-more-less-left_category">
			<a class="m-show-less-action" style="display: <?php echo $is_expand_category?'inline':'none'?>;"><?php echo $languages['showless'];?></a>
			<a class="m-show-more-action" style="display: <?php echo $is_expand_category?'none':'inline'?>;"><?php echo $languages['showmore'];?></a>
			<script type="text/javascript">(function ($) {
				$(document).trigger('m-show-more-reset', [
				    'left_category',
				    <?php echo $default_show_limit;?>,
				    <?php echo $is_expand_category?'true':'false'?>,
				    200,
				    0                ]);
			    })(jQuery);
			</script>
		    </div>
		</dd>
<!--END CATEGORY-->
<!--BEGIN PRICE-->
	    
    		<?php if($data['price_range']):?>
		    <dt class="even" data-id="m_left_price_filter" <?php echo ($is_series_type)?'style="display:none;"':'';?> ><?php echo $this->__('Price'); ?></dt>
		    <dd class="even" <?php echo ($is_series_type)?'style="display:none;"':'';?> >
                        <?php if(1==2) : // hidden old UI price  ?>
			<div class="m-slider-values left-aligned">
			    <span id="left_price-applied" class="m-slider-selected-value">
				<?php echo $this->__('from'); ?> <input type="text" class="m-slider m-from" size="2" value="<?php echo $data['price_range']['min']; ?>">
				<?php echo $this->__('to'); ?> <input type="text" class="m-slider m-to" size="2" value="<?php echo $data['price_range']['max']; ?>">
			    </span>
			</div>
                        <?php endif;?>
                        <ol class="m-filter-css-checkboxes">
                            <?php foreach ($arrayPrice as $prices_range => $prices_value) : ?>
			    <?php 
				if($prices_value['value'] == $priceSelected ){
                                    $checkPriceFormat = true;
                                    $prices_select = true;
				}else{
				    $prices_select = false;
				}
				?>
                            <li>
                                <a id="price-m-<?php echo $prices_range; ?>" class="<?php echo $prices_select ? 'm-checkbox-checked' : 'm-checkbox-unchecked'; ?>" 
                                   onclick="catalog_ajax.price_change('<?php echo $prices_value['min'];?>',<?php echo $prices_value['max'];?>)"
                                   title="<?php echo  $prices_value['name']; ?>" price-m-from=""><?php echo  $prices_value['name']; ?></a>
                            </li>
                            <?php endforeach; ?>
                        </ol>
                            
		    </dd>
		    <script type="text/javascript">
		    //<![CDATA[
                    $jq( document ).ready(function() {
                        <?php $arrayStr[] = $str;?>
                        var dataD = <?php echo json_encode($arrayStr) ?>;
                        catalog_ajax.getArrayPrice(<?php echo json_encode($arrayPrice)  ?>);
                        var checkMobile = <?php if($mobile){echo 1;}else{echo 0;}?>;
                        let priceD = '<?php if($checkPriceFormat){echo $priceSelected;}?>';
                        catalog_ajax.getDataFirstFilter(
                                dataD,
                                checkMobile,
                                priceD,
                                <?php if(isset($objCodeToDelete)){echo json_encode($objCodeToDelete);}?>);
                        if(checkMobile == 1){
                        $jq('.mb-mana-catalog-leftnav').appendTo('.modal-content');

                        }
                    });
		    ManaPro.filterRangeInput('left_price', {
			rangeFrom: <?php echo $data['price_range']['price_range']['min']; ?>,
			rangeTo: <?php echo $data['price_range']['price_range']['max']; ?>,
			url: '<?php echo  Mage::helper('mana_core')->base64EncodeUrl('#.') ?>',
			clearUrl: '<?php echo  Mage::helper('mana_core')->base64EncodeUrl('#.') ?>',
			formatThreshold: 0,
			decimalDigits: 0,
			decimalDigits2: 0,
			decimalSymbol: ",",
			groupSymbol: "."
		    });
		    //]]>
		    </script>
		<?php endif; ?>
<!--END PRICE-->
<!--BEGIN ATTRIBUTE-->
		<div id="menu-attributes">
		<?php foreach ($data['attributes'] as $attribute): ?>
		    <?php if(sizeof($attribute['options']) > 0):?>
			<dt class="odd" data-id="m_left_book_layout_filter"><?php echo $attribute['label'];?></dt>
			<dd class="odd">
			    <ol class="m-filter-css-checkboxes ">
				<?php foreach ($attribute['options'] as $option): ?>
				    <li>
					<a class="<?php echo $option['selected']?'m-checkbox-checked' : 'm-checkbox-unchecked'; ?>" id="m-left-attr-<?php echo $attribute['code'].$option['id'];?>" onclick="catalog_ajax.attribute_click('<?php echo $attribute['code'];?>',<?php echo $option['id'];?>)" 
					   title="<?php echo $option['label'];?>"><?php echo $option['label'];?></a>
					<?php echo $display_count?"(".$option['count'].")":'';?>
				    </li>
				<?php endforeach; ?>
			    </ol>
			    <div class="m-more-less" id="m-more-less-left_<?php echo $attribute['code'];?>">
				<a class="m-show-less-action" style="display: none;"><?php echo $languages['showless'];?></a>
				<a class="m-show-more-action" style="display: inline;"><?php 
				echo $languages['showmore'];
				?></a>
				<script type="text/javascript">(function ($) {
					$(document).trigger('m-show-more-reset', [
					    'left_<?php echo $attribute['code'];?>',
					    <?php echo $default_show_limit;?>,
					    false,
					    200,
					    0                ]);
				    })(jQuery);
				</script>
			    </div>
			</dd>
		    <?php endif; ?>
		<?php endforeach; ?>
		</div>
<!--END ATTRIBUTE-->
	    </dl>
	</div>
    </div>
</div>
<div id="m-wait" style="display: none;">
    <p class="loader" id="loading_mask_loader"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN, true); ?>/frontend/base/default/images/mana_core/m-wait.gif" alt="Loading..."><br>Please wait...</p>
</div>
<div class="m-overlay"></div>
<script type="text/javascript" src="<?php echo $CATALOG_SCRIPT; ?>"></script>
<script type="text/javascript">
    var catalog_ajax = new CatalogAjax();
    catalog_ajax.initCatalog(
	    <?php echo $cat_id;?>, 
	    <?php echo ($filters)?json_encode($filters, JSON_UNESCAPED_UNICODE):"{}";?>, 
	    <?php echo json_encode($currentPage);?>,
	    <?php echo ($limit)?json_encode($limit , JSON_UNESCAPED_UNICODE):"{}";?>, 
	    5,
	    <?php echo json_encode($order);?>, 
	    <?php echo ($data['attributes'])?json_encode($data['attributes'] , JSON_UNESCAPED_UNICODE):"{}";?>, 
	    <?php echo json_encode($languages, JSON_UNESCAPED_UNICODE);?>
	    ,<?php echo $is_series_type?'true':'false';?>
	    ,<?php echo $display_count?'true':'false';?>  
	);
</script>